
#
# Messages for Maps
#



#
# Map Names for (Automap) Descriptions
#	Note: This order must *NOT* change!
#
#	Note: The maximum description width is approximately:
#	  "Brotherhood of Steel (Lower Levels)" -- about 34 characters,
#	  but it's proportional, so you need to double-check it by
#	  going into mapper/game and going to the automap for that map.
#
#	Note: Descriptions *MUST* *NOT* be empty, and so temporary
#	  descriptions are just the map name itself (this also helps
#	  pinpoint unfinished ones when you go through here).
#
{100}{}{沙漠}				// DESERT1.MAP
{101}{}{沙漠}			    // DESERT2.MAP
{102}{}{沙漠}			    // DESERT3.MAP
{103}{}{阿羅由} 			  // arcaves.MAP
{104}{}{阿羅由} 			  // arvillag.MAP
{105}{}{阿羅由} 			  // arbridge.MAP
{106}{}{丹恩城} 			  // denbus1.MAP
{107}{}{丹恩城} 			     // denbus2.MAP
{108}{}{丹恩城} 			     // denres1.MAP
{109}{}{克拉馬斯城}			  // .MAP  ;Downtown
{110}{}{克拉馬斯城}			     // .MAP  ;Mall
{111}{}{克拉馬斯城}			     // .MAP  ;Rat Caves
{112}{}{克拉馬斯城}			     // .MAP  ;Toxic Caves
{113}{}{克拉馬斯城}			     // .MAP  ;Trapping Caves
{114}{}{克拉馬斯城}			     // .MAP  ;Grazing Area
{115}{}{地下掩體市} 		      // vctyctyd.MAP
{116}{}{地下掩體市} 		      // vctydwtn.MAP
{117}{}{地下掩體市} 		      // vctycocl.MAP
{118}{}{error:Map Name} 		       // .MAP
{119}{}{城市遺跡}			     // CITY1.MAP
{120}{}{海灣}				      // COAST1.MAP
{121}{}{海灣}				     // COAST2.MAP
{122}{}{沙漠}				     // COLATRUK.MAP
{123}{}{沙漠}				     // FSAUSER.MAP
{124}{}{error:Map Name} 			     // RAIDERS.MAP
{125}{}{error:Map Name} 			 // SHADYE.MAP
{126}{}{error:Map Name} 			 // SHADYW.MAP
{127}{}{error:Map Name} 				// GLOWENT.MAP
{128}{}{error:Map Name} 			    // LAADYTUM.MAP
{129}{}{error:Map Name} 			    // LAFOLLWR.MAP
{130}{}{error:Map Name} 		       // MBENT.MAP
{131}{}{error:Map Name} 		       // MBSTRG12.MAP
{132}{}{error:Map Name} 		       // MBVATS12.MAP
{133}{}{error:Map Name} 		       // MSTRLR12.MAP
{134}{}{error:Map Name} 		       // MSTRLR34.MAP
{135}{}{error:Map Name} 			    // V13ENT.MAP
{136}{}{error:Map Name} 				 // HUBENT.MAP
{137}{}{哈伯}				      // DETHCLAW.MAP
{138}{}{哈伯}				       // HUBDWNTN.MAP
{139}{}{哈伯}				       // HUBHEIGT.MAP
{140}{}{哈伯}				       // HUBOLDTN.MAP
{141}{}{哈伯}				       // HUBWATER.MAP
{142}{}{Glow}				      // GLOW1.MAP
{143}{}{Glow}				      // GLOW2.MAP
{144}{}{Boneyard}			      // LABLADES.MAP
{145}{}{Boneyard}			      // LARIPPER.MAP
{146}{}{Boneyard}			      // LAGUNRUN.MAP
{147}{}{Cathedral}			      // CHILDEAD.MAP
{148}{}{Military}			      // MBDEAD.MAP
{149}{}{Mountains}			      // MOUNTN1.MAP
{150}{}{Mountains}			      // MOUNTN2.MAP
{151}{}{Desert} 			      // FOOT.MAP
{152}{}{Desert} 			      // TARDIS.MAP
{153}{}{Desert} 			      // TALKCOW.MAP
{154}{}{Desert} 			      // USEDCAR.MAP
{155}{}{Brotherhood}			      // BRODEAD.MAP
{156}{}{Desert} 			      // DESCRVN1.MAP
{157}{}{Desert} 			      // DESCRVN2.MAP
{158}{}{Mountains}			      // MNTCRVN1.MAP
{159}{}{Mountains}			      // MNTCRVN2.MAP
{160}{}{Viper Camp}
{161}{}{Desert}
{162}{}{Mountains}
{163}{}{Desert}
{164}{}{Mountains}


#
# City elevation names -- AUTOMAP Names!
#
# Format: 3 (max elevations), by city
#
# 00: Desert, DESERT1.MAP
{200}{}{沙漠}
{201}{}{}
{202}{}{}
# 01: Desert, DESERT2.MAP
{203}{}{沙漠}
{204}{}{}
{205}{}{}
# 02: Desert, DESERT3.MAP
{206}{}{沙漠}
{207}{}{}
{208}{}{}
# 03: Arroyo Temple, ARCAVES.MAP
{209}{}{神殿：大廳}
{210}{}{神殿：走廊}
{211}{}{神殿：內殿}
# 04: Arroyo Village, .MAP
{212}{}{村莊}
{213}{}{}
{214}{}{}
# 05: Arroyo Bridge, .MAP
{215}{}{橋}
{216}{}{毀掉的橋}
{217}{}{}
# 06: Den, denbus1.MAP
{218}{}{商業區}
{219}{}{}
{220}{}{}
# 07: Den, denbus2.MAP
{221}{}{商業區}
{222}{}{}
{223}{}{}
# 08: Den, denres1.MAP
{224}{}{住宅區}
{225}{}{}
{226}{}{}
# 09: , .MAP ;Klamath Downtown
{227}{}{市中心}
{228}{}{市中心}
{229}{}{市中心}
# 10: , .MAP ;Klamath Mall
{230}{}{商場}
{231}{}{商場}
{232}{}{}
# 11: , .MAP ;Klamath Rat Caves
{233}{}{鼠洞}
{234}{}{鼠洞}
{235}{}{鼠洞}
# 12: , .MAP ;Klamath Toxic Caves
{236}{}{毒沼洞}
{237}{}{毒沼洞}
{238}{}{毒沼洞}
# 13: , .MAP ;Klamath Trapping Caves
{239}{}{狩獵區}
{240}{}{狩獵區}
{241}{}{狩獵區}
# 14: , .MAP ;Klamath Grazing Area
{242}{}{牧畜區}
{243}{}{牧畜區}
{244}{}{}
# 15: , .MAP ; Vault City Courtyard
{245}{}{廣場}
{246}{}{}
{247}{}{}
# 16: , .MAP ; Vault City Downtown
{248}{}{市中心}
{249}{}{}
{250}{}{}
# 17: , .MAP ; Vault City Council
{251}{}{市政區}
{252}{}{}
{253}{}{}
# 18: , .MAP ; Modoc Main Street
{254}{}{主街}
{255}{}{}
{256}{}{}
# 19: , .MAP ; Modoc Bed & Breakfast
{257}{}{旅店}
{258}{}{}
{259}{}{}
# 20: , .MAP ; Modoc Brahmin Pastures
{260}{}{牧場}
{261}{}{}
{262}{}{}
# 21: , .MAP ; Modoc Farrel's Garden
{263}{}{費爾的花園}
{264}{}{}
{265}{}{}
# 22: , .MAP ; Modoc Down the Shitter
{266}{}{山洞}
{267}{}{}
{268}{}{}
# 23: , .MAP ; Modoc Town Hall
{269}{}{鎮噴水池}
{270}{}{}
{271}{}{}
# 24: , .MAP ; Modoc Ghost Town: The Ghost Farm
{272}{}{農場}
{273}{}{}
{274}{}{}
# 25: , .MAP ; Modoc Ghost Town: Main Cavern
{275}{}{洞穴}
{276}{}{}
{277}{}{}
# 26: , .MAP ; Modoc Ghost Town: Underground Lake
{278}{}{地下湖}
{279}{}{}
{280}{}{}
# 27: , .MAP ; Sierra Army Depot: The Battlefield
{281}{}{戰場}
{282}{}{}
{283}{}{}
# 28: , .MAP ; Sierra Army Depot: Levels 1-3
{284}{}{人事區}
{285}{}{除存區}
{286}{}{機器實驗室}
# 29: , .MAP ; Sierra Army Depot: Level 4
{287}{}{生化研究區}
{288}{}{}
{289}{}{}
# 30: Vault City Vault, .MAP
{290}{}{避難所第一區}
{291}{}{避難所第二區}
{292}{}{避難所第三區}
# 31: Gecko Settlement
{293}{}{居住區}
{294}{}{居住區}
{295}{}{居住區}
# 32: Gecko Power Plant, .MAP
{296}{}{發電廠}
{297}{}{發電廠}
{298}{}{}
# 33: Gecko Junkyard, .MAP
{299}{}{廢物場}
{300}{}{廢物場}
{301}{}{廢物場}
# 34: Gecko Access Tunnels, .MAP
{302}{}{通道}
{303}{}{通道}
{304}{}{通道}
# 35: Arroyo Wilderness, .MAP
{305}{}{野外}
{306}{}{}
{307}{}{}
# 36: Vault 15, .MAP
{308}{}{１５號避難所第一區}
{309}{}{１５號避難所第二區}
{310}{}{１５號避難所第三區}
# 37: Vault 15, .MAP
{311}{}{流浪漢}
{312}{}{}
{313}{}{}
# 38: Vault 15, .MAP
{314}{}{流浪漢}
{315}{}{}
{316}{}{}
# 39: Vault 15, .MAP
{317}{}{東邊入口}
{318}{}{}
{319}{}{}
# 40: Vault 13, .MAP
{320}{}{第一區}
{321}{}{第二區}
{322}{}{第三區}
# 41: Vault 13, .MAP
{323}{}{洞穴}
{324}{}{}
{325}{}{}
# 42: NCR, .MAP
{326}{}{市中心}
{327}{}{}
{328}{}{}
# 43: NCR, .MAP
{329}{}{市政廳}
{330}{}{}
{331}{}{}
# 44: NCR, .MAP
{332}{}{衛斯丁牧場}
{333}{}{}
{334}{}{}
# 45: NCR, .MAP
{335}{}{牧畜地帶}
{336}{}{}
{337}{}{}
# 46: NCR, .MAP
{338}{}{市場}
{339}{}{}
{340}{}{}
# 47: NCR, .MAP
{341}{}{市政廳}
{342}{}{}
{343}{}{}
# 48: Klamath, klacanyn.MAP
{344}{}{溪谷}
{345}{}{溪谷}
{346}{}{溪谷}
# 49: Military Base, mbase12.MAP
{347}{}{第一區}
{348}{}{第二區}
{349}{}{}
# 50: Military Base, mbase34.MAP
{350}{}{第三區}
{351}{}{第四區}
{352}{}{}
# 51: Military Base, mbclose.MAP
{353}{}{入口}
{354}{}{}
{355}{}{}
# 52: Den Slave Run dnslvrun.MAP
{356}{}{沙漠}
{357}{}{村莊}
{358}{}{營地}
# 53: Car Desert out-of-gas, CarDesrt.MAP
{359}{}{沙漠}
{360}{}{}
{361}{}{}
# 54: New Reno 1 newr1.MAP
{362}{}{處女街}
{363}{}{兇徒賭場地下室}
{364}{}{兇徒賭場二樓}
# 55: New Reno 2 newr2.MAP
{365}{}{第二街}
{366}{}{暗樓}
{367}{}{鯊魚俱樂部三樓}
# 56: New Reno 3 newr3.MAP
{368}{}{商業區}
{369}{}{軍火店地下室}
{370}{}{}
# 57: New Reno 4 newr4.MAP
{371}{}{東邊}
{372}{}{火車站}
{373}{}{}
# 58: New Reno Chop Shop newrcs.MAP
{374}{}{店}
{375}{}{}
{376}{}{}
# 59: New Reno GO newrgo.MAP
{377}{}{墓場}
{378}{}{避難所}
{379}{}{}
# 60: New Reno ST newrst.MAP
{380}{}{}
{381}{}{實驗室}
{382}{}{}
# 61: New Reno Boxing Arena newrba.MAP
{383}{}{拳擊場}
{384}{}{拳擊場}
{385}{}{拳擊場}
# 62: Redding Wanamingo Mine Entrance  RedWame.Map
{386}{}{礦坑入口}
{387}{}{礦坑入口}
{388}{}{礦坑入口}
# 63: Great Wanamingo Mine, Level 1 and 2  RedWan1.MAP
{389}{}{礦坑第一區}
{390}{}{礦坑第二區}
{391}{}{}
# 64: Redding Downtown	RedDown.MAP
{392}{}{市中心}
{393}{}{市中心}
{394}{}{市中心}
# 65: Redding Mine Entrance   RedMEnt.MAP
{395}{}{礦坑入口}
{396}{}{礦坑入口}
{397}{}{礦坑入口}
# 66: Redding Downtown Tunnels	RedDTun.MAP
{398}{}{隧道}
{399}{}{隧道}
{400}{}{隧道}
# 67: Redding Mine Entrance Tunnels
{401}{}{隧道}
{402}{}{隧道}
{403}{}{隧道}
# 68: Random Encounter City 1
{404}{}{城市}
{405}{}{城市}
{406}{}{城市}
# 69: Random Encounter Cavern 0
{407}{}{山區}
{408}{}{山區}
{409}{}{山區}
# 70: Random Encounter Cavern 1
{410}{}{山洞}
{411}{}{山洞}
{412}{}{山洞}
# 71: Random Encounter Cavern 2
{413}{}{山洞}
{414}{}{山洞}
{415}{}{山洞}
# 72: Random Encounter Cavern 3
{416}{}{山洞}
{417}{}{山洞}
{418}{}{山洞}
# 73: Random Encounter Cavern 4
{419}{}{山洞}
{420}{}{山洞}
{421}{}{山洞}
# 74: Random Encounter Mountain 1
{422}{}{山區}
{423}{}{山區}
{424}{}{山區}
# 75: Random ncounter Mountain 2
{425}{}{山區}
{426}{}{山區}
{427}{}{山區}
# 76: Random Encounter Coast 1
{428}{}{海灣}
{429}{}{海灣}
{430}{}{海灣}
# 77: Random Encounter Coast 2
{431}{}{海灣}
{432}{}{海灣}
{433}{}{海灣}
# 78: Broken Hills 1  broken1.map
{434}{}{市中心}
{435}{}{地下室}
{436}{}{Unused}
# 79: Broken Hills 2 broken2.map
{437}{}{住宅區}
{438}{}{地下}
{439}{}{礦坑}
# 80: Random Encounter Cavern 5
{440}{}{山洞}
{441}{}{山洞}
{442}{}{山洞}
# 81: Random Encounter Desert 4
{443}{}{沙漠}
{444}{}{沙漠}
{445}{}{沙漠}
# 82. Random Encounter Desert 5
{446}{}{沙漠}
{447}{}{沙漠}
{448}{}{沙漠}
# 83. Random Encounter Desert 6
{449}{}{沙漠}
{450}{}{沙漠}
{451}{}{沙漠}
# 84. Random Encounter Desert 7
{452}{}{沙漠}
{453}{}{沙漠}
{454}{}{沙漠}
# 85. Random Encounter Coast 3
{455}{}{海灣}
{456}{}{海灣}
{457}{}{海灣}
# 86. Random Eer Coast 4
{458}{}{海灣}
{459}{}{海灣}
{460}{}{海灣}
# 87. Random Eer Coast 5
{461}{}{海灣}
{462}{}{海灣}
{463}{}{海灣}
# 88. Random Eer Coast 6
{464}{}{海灣}
{465}{}{海灣}
{466}{}{海灣}
# 89. Random Eer Coast 7
{467}{}{海灣}
{468}{}{海灣}
{469}{}{海灣}
# 90. Random Eer Coast 8
{470}{}{海灣}
{471}{}{海灣}
{472}{}{海灣}
# 91. Random Encounter Coast 9
{473}{}{海灣}
{474}{}{海灣}
{475}{}{海灣}
# 92. Raiders Camp 1
{476}{}{歹徒基地}
{477}{}{歹徒基地}
{478}{}{歹徒基地}
# 93. Raider Camp 2
{479}{}{山洞入口}
{480}{}{毒蠍巢穴}
{481}{}{兵營}
# 94. Broken Hills Random Encounter Desert
{482}{}{沙漠}
{483}{}{沙漠}
{484}{}{沙漠}
# 95. Broken om Encounter Mountain
{485}{}{山區}
{486}{}{山區}
{487}{}{山區}
# 96. Special: Whale
{488}{}{沙漠}
{489}{}{沙漠}
{490}{}{沙漠}
# 97. Special: Tin Woodsman
{491}{}{沙漠}
{492}{}{沙漠}
{493}{}{沙漠}
# 98. Special: Talking Head
{494}{}{沙漠}
{495}{}{沙漠}
{496}{}{沙漠}
# 99. Special: Federation Shuttle
{497}{}{沙漠}
{498}{}{沙漠}
{499}{}{沙漠}
# 100. Speciar: Unwashed Villagers
{500}{}{沙漠}
{501}{}{沙漠}
{502}{}{沙漠}
# 101. Special Encounter: Bridge
{503}{}{死亡之橋}
{504}{}{死亡之橋}
{505}{}{死亡之橋}
# 102. Special Encounter: Cafe of Broken Dreams
{506}{}{碎夢咖啡}
{507}{}{碎夢咖啡}
{508}{}{碎夢咖啡}
# 103. Special Encounter: Holy Hand Grenade 1
{509}{}{沙漠}
{510}{}{沙漠}
{511}{}{沙漠}
# 104. Special Encounter: Holy Hand Grenade 2
{512}{}{山區}
{513}{}{山洞}
{514}{}{山洞}
# 105. Special Encounter: Guardian of Forever
{515}{}{守護神}
{516}{}{１３號避難所}
{517}{}{１３號避難所}
# 106. Special Encounter: Toxic Waste Dump
{518}{}{毒廢料傾倒區}
{519}{}{毒廢料傾倒區}
{520}{}{毒廢料傾倒區}
# 107. Special Encounter: Pahiahs
{521}{}{沙漠}
{522}{}{沙漠}
{523}{}{沙漠}
# 108. Specialer: Mad Brahmin
{524}{}{沙漠}
{525}{}{沙漠}
{526}{}{沙漠}
# 109. Navarro Entrance
{527}{}{加油站}
{528}{}{地下}
{529}{}{飛鳥基地}
# 110. Coast Encounter 10
{530}{}{海岸線}
{531}{}{海岸線}
{532}{}{海岸線}
# 111. Coast En
{533}{}{海岸線}
{534}{}{海岸線}
{535}{}{海岸線}
# 112. Coast En
{536}{}{海岸線}
{537}{}{海岸線}
{538}{}{海岸線}
# 113. Desert Encounter 8
{539}{}{沙漠}
{540}{}{沙漠}
{541}{}{沙漠}
# 114. Desert Er 9
{542}{}{沙漠}
{543}{}{沙漠}
{544}{}{沙漠}
# 115. Desert Er 10
{545}{}{沙漠}
{546}{}{沙漠}
{547}{}{沙漠}
# 116. Desert Er 11
{548}{}{沙漠}
{549}{}{沙漠}
{550}{}{沙漠}
# 117. Desert Er 12
{551}{}{沙漠}
{552}{}{沙漠}
{553}{}{沙漠}
# 118. Cavern Encounter 5
{554}{}{山洞}
{555}{}{山洞}
{556}{}{山洞}
# 119. Cavern er 6
{557}{}{山洞}
{558}{}{山洞}
{559}{}{山洞}
# 120. Cavern er 7
{560}{}{山洞}
{561}{}{山洞}
{562}{}{山洞}
# 121. Mountain Encounter 3
{563}{}{山區}
{564}{}{山區}
{565}{}{山區}
# 122. Mountaier 4
{566}{}{山區}
{567}{}{山區}
{568}{}{山區}
# 123. Mountaier 5
{569}{}{山區}
{570}{}{山區}
{571}{}{山區}
# 124. Mountaier 6
{572}{}{山區}
{573}{}{山區}
{574}{}{山區}
# 125. City Encounter
{575}{}{遺棄的城市}
{576}{}{城市荒野}
{577}{}{城市荒野}
# 126. Arroyo Temple
{578}{}{神殿入口}
{579}{}{神殿入口}
{580}{}{神殿入口}
# 127. Destroyed Arroyo
{581}{}{被摧毀的橋}
{582}{}{被摧毀的橋}
{583}{}{被摧毀的橋}
# [Map 128] lookup_name=Enclave Detention
{584}{}{牢房}
{585}{}{牢房}
{586}{}{牢房}
# [Map 129] lookup_name=Enclave Dock
{587}{}{碼頭}
{588}{}{碼頭}
{589}{}{碼頭}
# [Map 130] lookup_name=Enclave End Fight
{590}{}{英克雷}
{591}{}{英克雷}
{592}{}{英克雷}
# [Map 131] lookup_name=Enclave Guard Barracks
{593}{}{軍營}
{594}{}{軍營}
{595}{}{軍營}
# [Map 132] lookup_name=Enclave Presidential
{596}{}{監督者}
{597}{}{監督者}
{598}{}{監督者}
# [Map 133] lookup_name=Enclave Reactor
{599}{}{反應爐}
{600}{}{反應爐}
{601}{}{反應爐}
# [Map 134] lookup_name=Enclave Trap Room
{602}{}{通道}
{603}{}{通道}
{604}{}{通道}
# [Map 135] lookup_name=San Fran Tanker
{605}{}{油輪}
{606}{}{油輪}
{607}{}{油輪}
# [Map 136] lookup_name=San Fran Dock
{608}{}{碼頭}
{609}{}{碼頭}
{610}{}{碼頭}
# [Map 137] lookup_name=San Fran China
{611}{}{中國城}
{612}{}{中國城}
{613}{}{中國城}
# 138. Shuttle Exterior
{614}{}{太空梭停留區}
{615}{}{太空梭停留區}
{616}{}{太空梭停留區}
# 139. Shuttle Interior
{617}{}{太空梭內部}
{618}{}{太空梭內部}
{619}{}{太空梭內部}
# 140. Hubologist Base
{620}{}{哈伯教基地}
{621}{}{哈伯教基地}
{622}{}{哈伯教基地}
# 141. City Encounter 3
{623}{}{摧毀的城市}
{624}{}{摧毀的城市}
{625}{}{摧毀的城市}
# 142. City Encount
{626}{}{摧毀的城市}
{627}{}{摧毀的城市}
{628}{}{摧毀的城市}
# 143. City Encount
{629}{}{摧毀的城市}
{630}{}{摧毀的城市}
{631}{}{摧毀的城市}
# 144. City Encount
{632}{}{摧毀的城市}
{633}{}{摧毀的城市}
{634}{}{摧毀的城市}
# 145. City Encount
{635}{}{摧毀的城市}
{636}{}{摧毀的城市}
{637}{}{摧毀的城市}
# 146. City Encount
{638}{}{摧毀的城市}
{639}{}{摧毀的城市}
{640}{}{摧毀的城市}
# 147. New Reno VB  newrvb.MAP
{641}{}{飛鳥區}
{642}{}{飛鳥區}
{643}{}{飛鳥區}
# 148. Shi Temple
{644}{}{始族神廟}
{645}{}{始族神廟}
{646}{}{始族神廟}
# 149. In Game Movie
{647}{}{沙漠}
{648}{}{沙漠}
{649}{}{沙漠}
# 150. RndBess
{650}{}{沙漠}
{651}{}{沙漠}
{652}{}{沙漠}


#
#	Short City names
#
{1500}{}{阿羅由}
{1501}{}{丹恩城}
{1502}{}{克拉馬斯}
{1503}{}{摩多克城}
{1504}{}{地下掩體市}
{1505}{}{蜥蝪城}
{1506}{}{破碎丘}
{1507}{}{新里諾}
{1508}{}{山嶺軍事基地}
{1509}{}{第１５號避難所}
{1510}{}{新加州共和國}
{1511}{}{第１３號避難所}
{1512}{}{軍事基地}
{1513}{}{瑞丁城}
{1514}{}{三番市}
{1515}{}{那瓦羅}
{1516}{}{英克雷}
{1517}{}{沙漠}		 # Abbey
{1518}{}{沙漠}		 # Primitive Tribe
{1519}{}{沙漠}		 # EPA
{1520}{}{鬼農場}
{1521}{}{沒能源的車}
{1522}{}{阿羅由}
{1523}{}{毒沼洞}
{1524}{}{丹恩城奴隸區}
{1525}{}{歹徒}
{1526}{}{沙漠}
{1527}{}{山區}
{1528}{}{城市荒野}
{1529}{}{海灣}
{1530}{}{葛洛沙}
{1531}{}{鯨魚}
{1532}{}{山林裡的人}
{1533}{}{說話的頭}
{1534}{}{聯邦太空船}
{1535}{}{村人}
{1536}{}{橋}
{1537}{}{碎夢咖啡}
{1538}{}{派拉丁}
{1539}{}{鼠洞}
{1540}{}{永恆守護神}
{1541}{}{毒廢料傾倒區}
{1542}{}{派拉斯}
{1543}{}{瘋牛}
{1544}{}{山洞}
{1545}{}{第１３號避難所}
{1546}{}{假的第１３號避難所}
{1547}{}{奇特遭遇}
{1548}{}{馬廄}
