#############################################################
#  Message File: Door.msg                                   #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the name which will  #
#           be displayed for critter or items when they     #
#           get hit. Each script from scripts.lst should    #
#           have a name associated with it.                 #
#                                                           #
#  Created: October 06, 1997                                #
#############################################################

{101}{}{}                               # obj_dude.int    ; Player script.
{102}{}{測試0}                          # Test0.int       ; Used to Test Scripts
{103}{}{測試1}                          # Test1.int       ; Used to Test Scripts
{104}{}{測試2}                          # Test2.int       ; Used to Test Scripts
{105}{}{測試3}                          # Test3.int       ; Used to Test Scripts
{106}{}{測試4}                          # Test4.int       ; Used to Test Scripts
{107}{}{測試5}                          # Test5.int       ; Used to Test Scripts
{108}{}{阿羅由戰士}                     # ACWarior.int    ; Generic Warrior in Arroyo
{109}{}{阿羅由村民}                     # ACVillgr.int    ; Generic Villager of Arroyo
{110}{}{曼那克}                         # ACMynoc.int     ; Mynoc, Bridge Guard of Arroyo
{111}{}{阿羅由長老}                     # AHElder.int     ; Elder of Arroyo
{112}{}{哈庫林}                         # AHHakun.int     ; Hakunin, Shaman of Arroyo
{113}{}{門}                             # Door.int        ; generic locked and trapped door
{114}{}{一般的}                         # Generic.int     ; Generic dialog for scripts
{115}{}{箱子}                           # AILkBox.int     ; Locked box in Arroyo Elder's room
{116}{}{上鎖的盒子}                     # Containr.int    ; Generic locked and trapped container
{117}{}{雙頭牛}                         # ACBrahmn.int    ; Brahmin for pen in Arroyo
{118}{}{胞子植物}                       # ACSporPl.int    ; Spore plants in Arroyo
{119}{}{}                               # ZClRat.int      ; Generic lesser rat
{120}{}{小毒蠍}                         # ZClScorp.int    ; Generic lesser scorpion
{121}{}{小螳螂}                         # ZClManti.int    ; Generic lesser mantis
{122}{}{小死亡爪}                       # ZClDthCL.int    ; Generic lesser death claw
{123}{}{花瓶}                           # AIVase.int      ; Vase in Arroyo Villager's Hut
{124}{}{箱子}                           # AIChest.int     ; Chest in Arroyo Shaman's Hut
{125}{}{阿羅由山洞}                     # ArCaves.int     ; Map Script for Arroyo Caves
{126}{}{木門}                           # DoorL100.int    ; Generic Locked Door (+100%) (Wood)
{127}{}{阿羅由村}                       # ArVillag.int    ; Map Script for Arroyo Village
{128}{}{阿羅由橋}                       # ArBridge.int    ; Map Script for Arroyo Bridge
{129}{}{老舊的門}                       # AICavDor.int    ; Locked wooden door in Arroyo Caves (0/-20)
{130}{}{地板}                           # SprTrp0.int     ; Generic spear Trap (0)
{131}{}{地板}                           # SprTrp50.int    ; Arroyo Spear Trap for Caves (50)
{132}{}{地板}                           # SprTrp51.int    ; Arroyo Spear Trap for Caves (50)
{133}{}{地板}                           # SprTrp52.int    ; Arroyo Spear Trap for Caves (50)
{134}{}{地板}                           # SprTrp53.int    ; Arroyo Spear Trap for Caves (50)
{135}{}{門}                             # AIBkDor.int     ; Door w/out a handle In Arroyo Caves
{136}{}{上癮}                           # DCAddict.int    ; Addict from the Den
{137}{}{士兵}                           # DCG2Grd.int     ; Gang 2 Guard from the Den
{138}{}{鎮民}                           # DCCustmr.int    ; Generic Customer in the Den
{139}{}{暴徒}                           # DCCustmr.int    ; Thug in the Den
{140}{}{孤兒}                           # DCOrphan.int    ; Thieving Orphan in the Den
{141}{}{喬伊}                           # DCJoey.int      ; Special thug in the Den
{142}{}{富力克}                         # DCFlick.int     ; Kwik N Save store owner in the Den
{143}{}{士兵}                           # DCG2Grd.int     ; Gang 2 Guard in the Den
{144}{}{彼特}                           # DCPetey.int     ; Petey, the alley addict in the Den
{145}{}{史密提}                         # DCSmitty.int    ; Smitty the junkyard guy in the Den
{146}{}{麥塔則}                         # dcMetzge.int    ; Metzger the Slaver in the Den
{147}{}{奴隸商人}                       # DCSlaver.int    ; Regular Slaver in the Den
{148}{}{塔比}                           # DCTubby.int     ; Tubby the store owner in the Den
{149}{}{安娜}                           # DCAnna.int      ; Anna the Ghost in the Den
{150}{}{伊克}                           # DCVic.int       ; Trader Vic in the Den, can be a party member
{151}{}{法蘭基}                         # DCFranki.int    ; Frankie, owner of the Hole in the Den
{152}{}{麗蓓嘉}                         # DCRebecc.int    ; Rebecca in the Den
{153}{}{比利}                           # DCBilly.int     ; One-tooth Billy in the Hole in the Den
{154}{}{希拉}                           # DCSheila.int    ; Sheila, the prostitute in the Hole in the Den
{155}{}{媽媽桑}                         # DCMom.int       ; Mom, who run's Mom's in the Den
{156}{}{村人}                           # DCSlvRun.int    ; Generic People for Slave Runs
{157}{}{抓苦力}                         # DNSlvRun.int    ; Map Script for Den Slave Runs
{158}{}{運奴車}                         # DISlvCrt.int    ; Slave Cart to take the Player to Den
{159}{}{丹恩城商業區}                   # DenBus1.int     ; Map Script for Den business area 1
{160}{}{丹恩城商業區}                   # DenBus2.int     ; Map Script for Den business area 2
{161}{}{丹恩城住宅區}                   # DenRes1.int     ; Map Script for Den residential area
{162}{}{墳墓}                           # diAnnGrv.int    ; Grave of Anna the ghost in the Den
{163}{}{墳墓}                           # diDadGrv.int    ; Grave of Anna the ghost's Dad in the Den
{164}{}{墳墓}                           # diMomGrv.int    ; Grave of Anna the ghost's Mom in the Den
{165}{}{屍骨}                           # diBones.int     ; Bones of Anna the ghost in the Den
{166}{}{日記}                           # diDiary.int     ; Diary of Anna the ghost in the Den
{167}{}{項鍊}                           # diLocket.int    ; Locket of Anna the ghost in the Den
{168}{}{蒸餾器}                         # diStill.int     ; Still that Maggie has in the basement in the Den
{169}{}{墳墓}                           # ziGenGrv.int    ; Generic grave
{170}{}{二十一點}                       # ziBlkJck.int    ; Generic black jack table
{171}{}{奴隸}                           # zcSlave.int     ; Generic slave
{172}{}{二十一點}                       # dcBlkJck.int    ; Den black jack table from Maggie's place
{173}{}{門}                             # diChcDor.int    ; Church door from the Den
{174}{}{威士忌包伯}                     # KCBob.int       ; Whiskey Bob from Klamath
{175}{}{骰子}                           # dcCraps.int     ; Maggie Craps dealer in the den
{176}{}{艾爾多}                         # KCAldo.int      ; Aldo from Klamath
{177}{}{艾丁}                           # KCArdin.int     ; Ardin from Klamath
{178}{}{小孩}                           # KChild.int      ; Child from Klamath
{179}{}{市民}                           # KCitizen.int    ; Citizen from Klamath
{180}{}{麥達}                           # KCMaida.int     ; Maida from Klamath
{181}{}{沙賈}                           # KCSajag.int     ; Sajag from Klamath
{182}{}{莎麗}                           # KCSally.int     ; Sally from Klamath
{183}{}{史麥力}                         # KCSmiley.int    ; Smiley from Klamath
{184}{}{珍妮}                           # KCJenny.int     ; Jenny from Klamath
{185}{}{史林}                           # KCSlim.int      ; Slim from Klamath
{186}{}{托爾}                           # KCTorr.int      ; Torr from Klamath
{187}{}{丹頓}                           # KCDunton.int    ; Dunton from Klamath
{188}{}{公民}                           # VCCrtCit.int    ; Vault City Courtyard Citizen
{189}{}{旅行者}                         # VCCrtOut.int    ; Vault City Courtyard Outsider
{190}{}{地下掩體市衛兵}                 # VCCrtGrd.int    ; Vault City Courtyard Guard
{191}{}{地下掩體市衛兵}                 # VCInGrd.int     ; Vault City Inner Guard
{192}{}{史提夫}                         # VCSteve.int     ; Steve from Vault City
{193}{}{安迪爾}                         # VCAndy.int      ; Andy the Medic in the Central Vault City
{194}{}{地下掩體市衛兵}                 # VCGatGrd.int    ; Vault City Main Gate Guard
{195}{}{裘伊醫生}                       # VCDrTroy.int    ; Vault City Dr. Troy in the Vault
{196}{}{土狗}                           # KCYellow.int    ; Yellow Dog in Klamath
{197}{}{巴爾賽斯}                       # mcBaltha.int    ; Balthas in Modoc
{198}{}{孔尼洛斯}                       # mcCornel.int    ; Cornelius in Modoc
{199}{}{達賓}                           # mcDavin.int     ; Davin in Modoc
{200}{}{費爾}                           # mcFarrel.int    ; Farrel in Modoc
{201}{}{葛力斯韓}                       # mcGrisha.int    ; Grisham in Modoc
{202}{}{喬}                             # mcJo.int        ; Jo in Modoc
{203}{}{喬尼}                           # mcJonny.int     ; Jonny in Modoc
{204}{}{卡爾}                           # mcKarl.int      ; Karl in Modoc
{205}{}{拉帝}                           # mcLaddie.int    ; Laddie in Modoc
{206}{}{麥麗雅}                         # mcMiria.int     ; Miria in Modoc
{207}{}{保護者}                         # mcProtec.int    ; Protector in Modoc
{208}{}{蘿絲}                           # mcRose.int      ; Rose in Modoc
{209}{}{比格}                           # mcVegeir.int    ; Vegeir in Modoc
{210}{}{愛德}                           # VCEd.int        ; Ed the Brahma dealer in Vault City
{211}{}{哈利}                           # VCHarry.int     ; Happy Harry the store keep in Vault City
{212}{}{史密斯太太}                     # VCFSmith.int    ; Mrs. Smith from Vault City (Farmer)
{213}{}{麥琳達}                         # VCMelind.int    ; Town Greeter Melinda, Vault City
{214}{}{蜥蝪獵人}                       # KCTrapr.int     ; Generic trapper in Klamath
{215}{}{史密斯先生}                     # VCMSmith.int    ; Mr. Smith from Vault City (Farmer)
{216}{}{史其夫}                         # VCSkeeve.int    ; Skeeve, sells fake passes to Vault City
{217}{}{葛列格理地方官}                 # VCGreg.int      ; Proconsul Gregory of Vault City
{218}{}{南西護士}                       # VCNancy.int     ; Nurse Nancy in Vault City
{219}{}{藍提爾}                         # VCRandal.int    ; Chief Admenities Officer of Vault City
{220}{}{黏液}                           # KTGoo.int       ; Toxic Goo in the rat caves (Klamath)
{221}{}{巴爾可斯}                       # VCBarkus.int    ; Barkus, Vault City Service Coordinator
{222}{}{村民}                           # VCGenVil.int    ; Generic Villager around Vault City
{223}{}{史塔克}                         # VCStark.int     ; Vault City Sargent Stark
{224}{}{地下掩體市衛兵}                 # VCVltGrd.int    ; Guard for entrance into the Vault of VC
{225}{}{老僑}                           # VCOldJoe.int    ; Crazy Old Joe (Vault City)
{226}{}{康爾}                           # VCConnar.int    ; Connar from Vault City
{227}{}{瓦樂斯}                         # VCWalace.int    ; Wallace the Customs Official (Vault City)
{228}{}{琳娜特}                         # VCLynett.int    ; First Citizen Lynette of Vault City
{229}{}{麥卡路}                         # VCMClure.int    ; Senior Council Member MCclure (Vault City)
{230}{}{變種鼠}                         # GCBrain.int     ; Intelligent rat in Gecko
{231}{}{費斯特}                         # GCFestus.int    ; Festering ghoul in Gecko
{232}{}{格登}                           # GCGordon.int    ; Ghoul with economic data in Gecko
{233}{}{韓克}                           # GCHank.int      ; Ghoul that monitors the reactor in Gecko
{234}{}{傑米}                           # GCJerem.int     ; Ghoul in charge of supply cabinet in Gecko
{235}{}{藍爾皮}                         # GCLumpy.int     ; Watches the Brahmin and helps Skeeter
{236}{}{史蓋特}                         # GCSkeetr.int    ; Gadgeteer in Gecko
{237}{}{祖可}                           # GCZomak.int     ; Muscle man for the Brain
{238}{}{伍茲}                           # GCWooz.int      ; Bar owner and Tragic player
{239}{}{廉尼}                           # GCLenny.int     ; Stuttering ghoul that can join party
{240}{}{僵屍衛兵}                       # GGCRDesk.int    ; Reactor Desk guard
{241}{}{僵屍工人}                       # GCRWorkr.int    ; Reactor worker
{242}{}{發光的工人}                     # GCRGlow.int     ; Reactor glowing one
{243}{}{僵屍衛兵}                       # GCRGuard.int    ; Reactor guard
{244}{}{機器人}                         # GCRRobot.int    ; Reactor robot
{245}{}{僵屍市民}                       # GCFolk.int      ; Townsfolk in Gecko
{246}{}{地圖}                           # DepoLv1.int     ; Map script for Sierra Army Depot, Level 1
{247}{}{地圖}                           # DepoLvA.int     ; Map script for Sierra Army Depot Undergound
{248}{}{地圖}                           # DepoLvB.int     ; Map script for Sierra. Underground B
{249}{}{安全機器人}                     # WCSecBot.int    ; Sierra Base, Security Robot (generic)
{250}{}{維修機器人}                     # WCRepBot.int    ; Sierra Base, Repair Robot (generic)
{251}{}{實體顯像磁片}                   # WIEvcDsk.int    ; Sierra Base, Evacution Holodisk
{252}{}{實體顯像磁片}                   # WIMedDsk.int    ; Sierra Base, Medical Log 1 Holodisk
{253}{}{實體顯像磁片}                   # WIExpDsk.int    ; Sierra Base, Experiment Log Holodisk
{254}{}{控制器}                         # WSTerm1A.int    ; Security Computer, Level 1 -- Sierra Base
{255}{}{控制器}                         # WSTerm1B.int    ; Security Systems, Level 1 -- Sierra Base
{256}{}{控制器}                         # WSTerm2A.int    ; Security Computer, Level 2 -- Sierra Base
{257}{}{控制器}                         # WSTerm2B.int    ; Security Systems, Level 2 -- Sierra Base
{258}{}{控制器}                         # WSTerm2C.int    ; Auto Repair System, Level 2 -- Sierra Base
{259}{}{控制器}                         # WSTerm3A.int    ; Security Computer, Level 3 -- Sierra Base
{260}{}{控制器}                         # WSTerm3B.int    ; Skynet Terminal, Level 3 -- Sierra Base
{261}{}{控制器}                         # WSTerm3C.int    ; Robobrain Activator, Level 3 -- Sierra Base
{262}{}{控制器}                         # WSTerm4A.int    ; Security Computer, Level 4 -- Sierra Base
{263}{}{控制器}                         # WSTerm4B.int    ; Organ Extractor, Level 4 -- Sierra Base
{264}{}{控制器}                         # WSTerm4C.int    ; BioStorage Computer, Level 4 -- Sierra Base
{265}{}{紙片}                           # WIPaswrd.int    ; Piece of paper with the password on it
{266}{}{度伯士兵}                       # WCDobbs.int     ; Private Dobbs, Sierra Army Depot
{267}{}{中央機器人}                     # WCBrnBot.int    ; Brain Bot in the Army Depot
{268}{}{電梯}                           # ZSElev01.int    ; Generic Elevator
{269}{}{電梯}                           # ZSElev02.int    ; Generic Elevator
{270}{}{鎖上的箱子}                     # DITubBox.int    ; Tubby's box of inventory
{271}{}{鎖上的箱子}                     # DIFlkBox.int    ; Flick's box of inventory
{272}{}{坦蒂}                           # SHTandi.int     ; Tandi the talking head in the NCR2 area
{273}{}{刺針陷阱}                       # ATSrTrp0.int    ; Arroyo Spear Trap for Caves (50)
{274}{}{刺針陷阱}                       # ATSrTrp1.int    ; Arroyo Spear Trap for Caves (50)
{275}{}{刺針陷阱}                       # ATSrTrp2.int    ; Arroyo Spear Trap for Caves (50)
{276}{}{刺針陷阱}                       # ATSrTrp3.int    ; Arroyo Spear Trap for Caves (50)
{277}{}{刺針陷阱}                       # ATSrTrp4.int    ; Arroyo Spear Trap for Caves (50)
{278}{}{刺針陷阱}                       # ATSrTrp5.int    ; Arroyo Spear Trap for Caves (50)
{279}{}{刺針陷阱}                       # ATSrTrp6.int    ; Arroyo Spear Trap for Caves (50)
{280}{}{刺針陷阱}                       # ATSrTrp7.int    ; Arroyo Spear Trap for Caves (50)
{281}{}{刺針陷阱}                       # ATSrTrp8.int    ; Arroyo Spear Trap for Caves (50)
{282}{}{刺針陷阱}                       # ATSrTrp9.int    ; Arroyo Spear Trap for Caves (50)
{283}{}{刺針陷阱}                       # ATSrTrpA.int    ; Arroyo Spear Trap for Caves (50)
{284}{}{刺針陷阱}                       # ATSrTrpB.int    ; Arroyo Spear Trap for Caves (50)
{285}{}{刺針陷阱}                       # ATSrTrpC.int    ; Arroyo Spear Trap for Caves (50)
{286}{}{刺針陷阱}                       # ATSrTrpD.int    ; Arroyo Spear Trap for Caves (50)
{287}{}{刺針陷阱}                       # ATSrTrpE.int    ; Arroyo Spear Trap for Caves (50)
{288}{}{刺針陷阱}                       # ATSrTrpF.int    ; Arroyo Spear Trap for Caves (50)
{289}{}{鬼山洞一}                       # GstCav1.int     ; Modoc Ghost Cave 1
{290}{}{鬼山洞二}                       # GstCav2.int     ; Modoc Ghost Cave 2
{291}{}{鬼農場}                         # GstFarm.int     ; Modoc Ghost Farm
{292}{}{摩多克城牧場}			# ModBrah.int     ; Modoc Brahmin Field
{293}{}{摩多克城花園}                   # ModGard.int     ; Modoc Garden
{294}{}{摩多克城旅店}                   # ModInn.int      ; Modoc Inn
{295}{}{摩多克城總幹線}                 # ModMain.int     ; Modoc Main
{296}{}{摩多克城!#&^}                   # ModShit.int     ; Modoc under the shitter
{297}{}{摩多克水井}                     # ModWell.int     ; Modoc Well
{298}{}{新加州共和國第二區}             # ncr2.int        ; NCR area 2
{299}{}{阿羅由花園}                     # ArGarden.int    ; Arroyo Gardens map script
{300}{}{蜥蝪人}                         # ACGecko.int     ; generic Gecko creature
{301}{}{布拉克花}                       # AIBroc.int      ; Arroyo Broc Flower
{302}{}{山德根}                         # AIXander.int    ; Arroyo Xander Root
{303}{}{雙頭牛}                         # ZCBrahmn.int    ; Generic Brahmin
{304}{}{巴爾塞克之妻}                   # mcBalWif.int    ; Modoc Balthas wife
{305}{}{雙頭牛}                         # mcBrahmn.int    ; Modoc brahmin
{306}{}{野狗}                           # mcAtkDog.int    ; Modoc Attack Dog
{307}{}{石頭}                           # miDclRks.int    ; Modoc Rocks in front of the death claw cage
{308}{}{石頭}                           # miShtRks.int    ; Modoc Rocks under the shitter
{309}{}{保險箱}                         # miWalSfe.int    ; Modoc Farrel's wall safe
{310}{}{錢袋}                           # miCoinBg.int    ; Modoc Coin bags at the bottom of the well
{311}{}{廁所}                           # miToilet.int    ; ; Modoc Toliet
{312}{}{箱子}                           # miLstFnd.int    ; Modoc Lost and Found at Rose's
{313}{}{喬登}                           # ACJordan.int    ; Jordan. Trains player in Melee
{314}{}{莫麗姑媽}                       # ACMorlis.int    ; Aunt Morlis. Has flint to give player
{315}{}{盧卡斯}                           # ACFist.int      ; Standing Fist. Trains player in Unarmed
{316}{}{費爾格斯}                       # ACEric.int      ; Whiny person asking to fix the well
{317}{}{井}                             # ASWell.int      ; Arroyo Well. It's broken. Fix w/ Repair
{318}{}{甘德}                           # OCGrutha.int    ; Vault 13 Gruthar Deathclaw leader
{319}{}{地圖}                           # Kladwtwn.int    ; Map script for Klamath Downtown
{320}{}{史蓋特}                         # SCSkeete.int    ; Skeeter dialog script for NCR Entrance area
{321}{}{那多兒}                         # ACNagor.int     ; You cousin who has lost his dog
{322}{}{飛煙}                           # ACDog.int       ; Nagor's dog Smoke
{323}{}{新加州共和國第一區}             # Ncr1.int        ; Ncr area 1 map
{324}{}{新加州共和國第三區}             # Ncr3.int        ; Ncr area 3 map
{325}{}{新加州共和國第四區}             # Ncr4.int        ; Ncr area 4 map
{326}{}{新加州共和國入口}               # Ncrent.int      ; Ncr area Entrance map
{327}{}{麥卡}                           # SCMikey.int     ; NCR Lizard Dealer
{328}{}{麥卡的箱子}                     # SIMbox.int      ' NCR Mikey's inventory box. (off Screen)
{329}{}{發射器}                         # WSEmit1a.int    ; Emitter, Level 1, Section A   (Sierra Base)
{330}{}{發射器}                         # WSEmit1b.int    ; Emitter, Level 1, Section B   (Sierra Base)
{331}{}{發射器}                         # WSEmit1c.int    ; Emitter, Level 1, Section C   (Sierra Base)
{332}{}{發射器}                         # WSEmit1d.int    ; Emitter, Level 1, Section D   (Sierra Base)
{333}{}{發射器}                         # WSEmit1e.int    ; Emitter, Level 1, Section E   (Sierra Base)
{334}{}{發射器}                         # WSEmit2a.int    ; Emitter, Level 2, Section A   (Sierra Base)
{335}{}{發射器}                         # WSEmit2b.int    ; Emitter, Level 2, Section B   (Sierra Base)
{336}{}{發射器}                         # WSEmit2c.int    ; Emitter, Level 2, Section C   (Sierra Base)
{337}{}{發射器}                         # WSEmit2d.int    ; Emitter, Level 2, Section D   (Sierra Base)
{338}{}{發射器}                         # WSEmit3a.int    ; Emitter, Level 3, Section A   (Sierra Base)
{339}{}{發射器}                         # WSEmit3b.int    ; Emitter, Level 3, Section B   (Sierra Base)
{340}{}{力場}                           # WSFeld1a.int    ; F. Field, Level 1, Section A   (Sierra Base)
{341}{}{力場}                           # WSFeld1b.int    ; F. Field, Level 1, Section B   (Sierra Base)
{342}{}{力場}                           # WSFeld1c.int    ; F. Field, Level 1, Section C   (Sierra Base)
{343}{}{力場}                           # WSFeld1d.int    ; F. Field, Level 1, Section D   (Sierra Base)
{344}{}{力場}                           # WSFeld1e.int    ; F. Field, Level 1, Section E   (Sierra Base)
{345}{}{力場}                           # WSFeld2a.int    ; F. Field, Level 2, Section A   (Sierra Base)
{346}{}{力場}                           # WSFeld2b.int    ; F. Field, Level 2, Section B   (Sierra Base)
{347}{}{力場}                           # WSFeld2c.int    ; F. Field, Level 2, Section C   (Sierra Base)
{348}{}{力場}                           # WSFeld2d.int    ; F. Field, Level 2, Section D   (Sierra Base)
{349}{}{力場}                           # WSFeld3a.int    ; F. Field, Level 3, Section A   (Sierra Base)
{350}{}{力場}                           # WSFeld3b.int    ; F. Field, Level 3, Section B   (Sierra Base)
{351}{}{警報器}                         # WSKlaxon.int    ; Changes lights to Flashing w/ Sierra on Alert
{352}{}{霸斯特}                         # SCBuster.int    ; Buster gun dealer at NCR entrance
{353}{}{書架}                           # SIShelf1.int    ; Busters shelves where items are kept
{354}{}{書架}                           # SIShelf2.int    ; Busters shelves where items are kept
{355}{}{歹徒}                           # SIShelf3.int    ; Busters shelves where items are kept
{356}{}{歹徒}                           # ECRaider.int    ; Random Encounter Raider
{357}{}{平民}                           # ECPeasnt.int    ; Random Encounter Peasant
{358}{}{商人}                           # ECMrchnt.int    ; Random Encounter Merchant
{359}{}{衛兵}                           # ECGuard.int     ; Random Encounter Gaurd
{360}{}{客人}                           # SCRawpat.int    ; Rawhide patron in NCR Entrance
{361}{}{地板}                           # WTElFlr2.int    ; Electric Floor on Level 2 Sierra Base
{362}{}{電漿陷阱}                       # WTPlTrp0.int    ; Plasma Trap for Sierra Base(-30)
{363}{}{電漿陷阱}                       # WTPlTrp1.int    ; Plasma Trap for Sierra Base(-30)
{364}{}{控制器}                         # WSPwrDwn.int    ; Power Switch for the Sierra Base
{365}{}{佈告欄}                         # KSBboard.int    ; Klamath bulletin board
{366}{}{大門}                           # ASCrlDr.int     ; Arroyo Corral Gate
{367}{}{黏液}                           # ATGoo.int       ; Goo in the Garden Map
{368}{}{門}                             # KSCVDoor.int    ; Door in Klamath Rat Caves
{369}{}{門}                             # KSMalldr.int    ; Door in Klamall..get key from Slim or Dog
{370}{}{蜥蝪}                           # ZCGecko.int     ; Generic gecko
{371}{}{金色蜥蝪}                       # ZCLGecko.int    ; Generic Golden Gecko
{372}{}{地圖}                           # 2ndSt.int       ; 2nd Street Map Script
{373}{}{地圖}                           # ChopShop.int    ; Chop Shop Map Script
{374}{}{地圖}                           # GeckPwpl.int    ; Gecko Power Plant Map Script
{375}{}{地圖}                           # GeckTunl.int    ; Gecko Tunnels Map Script
{376}{}{地圖}                           # KlaCnyn.int     ; Klamath Canyon Map Script
{377}{}{地圖}                           # MBase12.int     ; Military Base Level 1,2 Map Script
{378}{}{地圖}                           # MBase34.int     ; Military Base Level 3,4 Map Script
{379}{}{地圖}                           # MBClose.int     ; Military Base Closed Map Script
{380}{}{地圖}                           # ModShit.int     ; Map Script for Modoc Shitter
{381}{}{地圖}                           # NCR1.int        ; Map Script for NCR1
{382}{}{地圖}                           # NCR2.int        ; Map Script for NCR2
{383}{}{地圖}                           # NCR3.int        ; Map Script for NCR3
{384}{}{地圖}                           # NCR4.int        ; Map Script for NCR4
{385}{}{地圖}                           # NCREx.int       ; Map Script for NCR Exit
{386}{}{地圖}                           # Stable.int      ; Map Script for Stables
{387}{}{地圖}                           # V13_Orig.int    ; Map Script for Original Vault 13
{388}{}{地圖}                           # V13Ent.int      ; Map Script for Vault 13 Entrance
{389}{}{地圖}                           # V15_Orig.int    ; Map Script for Original Vault 15
{390}{}{地圖}                           # V15Ent.int      ; Map Script for Vault 15 Entrance
{391}{}{地圖}                           # Vault13.int     ; Map Script for Vault 13
{392}{}{地圖}                           # Vault15.int     ; Map Script for Vault 15
{393}{}{地圖}                           # VaultNec.int    ; Map Script for Necropolis Vault
{394}{}{地圖}                           # VCtyVlt.int     ; Map Script for Vault City Vault
{395}{}{地圖}                           # Virgin.int      ; Map Script for Virgin (these still exist?)
{396}{}{蒸餾器}                         # Kstill.int      ; Script for still in Klamath
{397}{}{酒吧顧客}                       # Kcggcust.int    ; Script for Klamath golden gecko customer
{398}{}{酒吧顧客}                       # Kcbhcust.int    ; Script for Klamath buckner house customer
{399}{}{沃爾斯}                         # SCVortis.int    ; Script for Vortis slave pen dude in NCR entrance
{400}{}{澡堂服務生}                     # Kcbgirl.int     ; Script for Klamath bath girl
{401}{}{奴隸}                           # SCSlaves.int    ; Script for NCR Entrance slaves
{402}{}{毒蠍子}                         # Kcscorp.int     ; Script for Klamath scorpions on the graze map
{403}{}{雙頭牛}                         # Kcbrahmn.int    ; Script for Klamath brahmin on the graze map
{404}{}{車}                             # ZSDrvCar.int    ; Drivable Car for the player
{405}{}{桌子}                           # diVicTbl.int    ; Den, table that Vic works at
{406}{}{地圖}                           # Klagraz.int     ; Map Script for Klamath graze map
{407}{}{地圖}                           # CarDesrt.int    ; Car Out of Gas Desert Map
{408}{}{地圖}                           # GeckSetl.int    ; Map Script for Gecko Settlememt
{409}{}{地圖}                           # VCtyCtyd.int    ; Map Script for Vault City Courtyard
{410}{}{可維嘉}                         # Kscorveg.int    ; Klamath broken car with fuel injection
{411}{}{地圖}                           # KlaToxCv.int    ; Klamath Toxic Caves  Map Script
{412}{}{鐵製地板}                       # SISlvdor.int    ; Slave pen door in NCR Entrance
{413}{}{地圖}                           # RndDsrt.int     ; Random Encounter Desert Map Script
{414}{}{地圖}                           # RndCoast.int    ; Random Encounter Coast Map Script
{415}{}{地圖}                           # RndMnt.int      ; Random Encounter Mountain Map Script
{416}{}{箱子}                           # Kidbox.int      ; Klamath dunton inventory box
{417}{}{箱子}                           # Kibbox.int      ; Klamath buckner inventory box
{418}{}{箱子}                           # Kisbox.int      ; Klamath sajag inventory box
{419}{}{拉契}                           # SCRatch.int     ; Ncr entrance JUNK dealer
{420}{}{拳擊手}                         # ncBoxer.int     ; New Reno Generic Boxer
{421}{}{邁可．麥尼力}                   # ncMcKnee.int    ; New Reno Mike McKneely
{422}{}{伊凡．好萊菲}                   # ncHollyf.int    ; New Reno Evan Hollyfeld
{423}{}{割碎機}                         # ncTyson.int     ; New Reno Mike Tyson
{424}{}{科學家}                         # ncScient.int    ; New Reno Generic Scientist
{425}{}{麥爾科}                         # SCMerk.int      ; Merk an NCR mob type guy
{426}{}{拳擊迷}                         # ncBoxFan.int    ; New Reno Boxing Fan
{427}{}{販毒者}                         # ncDrgDlr.int    ; New Reno Drug Dealer
{428}{}{賭客}                           # ncCasPat.int    ; New Reno Casino Patron
{429}{}{皮條客}                         # ncPimp.int      ; New Reno Generic Pimp
{430}{}{吸毒者}                         # ncJunkie.int    ; New Reno Generic Junkie
{431}{}{傢俱}                           # stuff.int       ; signals critters on steal attempt
{432}{}{地板}                           # trespass.int    ; same as stuff only for an area
{433}{}{格朗特}                         # ATDeath.int     ; Spatial telling the player about Nagor dead
{434}{}{實體顯像磁片}                   # SIFakhlo.int    ; Fake holodisk you get from Merk in NCR.
{435}{}{廉尼}                           # SCLenny.int     ; Lenny a guy in NCR Entrance
{436}{}{盒子}                           # SCPtbox.int     ; Players temp box to hold his stuff for the fight with lenny
{437}{}{妓女}                           # ncProsti.int    ; New Reno Prostitute with billions of messages
{438}{}{奴隸}                           # ncSlave.int     ; New Reno Slaves
{439}{}{瑞可}                           # ncRico.int      ; New Reno Rico, Monte's thug
{440}{}{Ａ片主角}                       # ncActres.int    ; New Reno Porn Actress
{441}{}{臨時演員}                       # ncFluffe.int    ; New Reno Porn Fluffer/Extra
{442}{}{地圖}                           # Klacanyn.int    ; Map script for Klamath Canyon
{443}{}{狼}                             # ECWlfPck.int    ; Military Base Wolf Pack
{444}{}{發電機}                         # ESPwrGen.int    ; Military Base Power Generator
{445}{}{門}                             # ESLkDor.int     ; Military Base Locked Door (-30)
{446}{}{超級變種人}                     # ECGenMut.int    ; Military Base Generic Mutant
{447}{}{沙爾瓦多的手下}                 # ncSalMen.int    ; New Reno Salvatore's Men
{448}{}{彼希的手下}                     # ncBisMen.int    ; New Reno Bishop's Men
{449}{}{莫丁諾的手下}                   # ncMorMen.int    ; New Reno Mordino's Men
{450}{}{萊特的孩子}                     # ncWriTee.int    ; New Reno Wright's Sons & Daughters
{451}{}{賭場保鑣}                       # ncCasBou.int    ; New Reno Generic Casino Bouncer
{452}{}{麥拉}                           # SCMira.int      ; NCR entrance bartender
{453}{}{新里諾處女街}                   # NewR1.int       ; New Reno Map Virgin Street
{454}{}{新里諾第二街}                   # NewR2.int       ; New Reno Map 2nd Street
{455}{}{新里諾商業區}                   # NewR3.int       ; New Reno Map Commercial Row
{456}{}{新里諾東區}                     # NewR4.int       ; New Reno Map East Side
{457}{}{新里諾馬棚}                     # NewRSt.int      ; New Reno Map Stables
{458}{}{新里諾肉店}                     # NewRCS.int      ; New Reno Map Chop Shop
{459}{}{新里諾葛洛沙}                   # NewRGo.int      ; New Reno Map Gologtha
{460}{}{新里諾彼希的地下室}             # NewRBa.int      ; New Reno Map Bishop Basement
{461}{}{實體顯像磁片}                   # EIOutDsk.int    ; Military Base Holodisk (Outside)
{462}{}{實體顯像磁片}                   # EILv1Dsk.int    ; Military Base Holodisk (Level 1)
{463}{}{實體顯像磁片}                   # EILv2Dsk.int    ; Military Base Holodisk (Level 2)
{464}{}{實體顯像磁片}                   # EILv3Dsk.int    ; Military Base Holodisk (Level 3)
{465}{}{實體顯像磁片}                   # EILv4Dsk.int    ; Military Base Holodisk (Level 4)
{466}{}{衛兵}                           # SCGteGrd.int    ; Ncr gate guard
{467}{}{礦車}                           # ESMinCrt.int    ; Military Base Mine Cart to explode on door
{468}{}{麥爾開}                         # ECMelchr.int    ; Melchoir the Magnificent (psuedo-mage)
{469}{}{變種野獸}                       # ECMutRat.int    ; Mutated Rats in Military Base
{470}{}{ＦＥＶ黏液}                     # ETGoo.int       ; FEV Goo in the Military Base
{471}{}{衛兵隊長}                       # SCGGCap.int     ; NCR Entrance Gate guard captain
{472}{}{奴隸工頭}                       # SCslvovr.int    ; NCR Entrance slave overseer
{473}{}{麥爾開的寵物}                   # ECMelPet.int    ; Melchior's Pets
{474}{}{奴隸商的衛兵}                   # SCslvgrd.int    ; Slaver Guard in NCR Entrance
{475}{}{門}                             # SIclsdor.int    ; Closing door
{476}{}{控制器}                         # SITerm.int      ; Slave pen terminals NCR Entrance
{477}{}{吃角子老虎}                     # ziSlots.int     ; Generic Slot Machine
{478}{}{小孩}                           # ncWriChi.int    ; New Wright children
{479}{}{西比}                           # ncSheb.int      ; New Reno Sheb
{480}{}{衛兵}                           # SCMrkGrd.int    ; Merk's guards NCR Entrance and council
{481}{}{發射器}                         # SIEmtr.int      ; Emitter in NCR Entrance
{482}{}{力場}                           # SIFField.int    ; Force field in NCR Entrance
{483}{}{史力克}                         # Kcsulik.int     ; Sulik from Klamath
{484}{}{亨利醫生}                       # SCHenry.int     ; Henry NCR Entrance
{485}{}{衛兵}                           # SCCarGrd.int    ; Carlson's guards NCR2
{486}{}{卡洛森衛兵攻擊}                 # STCaratk.int    ; Carlson's guards attack spatial
{487}{}{卡洛森守門兵}                   # SCcgtgrd.int    ; Carlson's gate Guards
{488}{}{囚犯}                           # VCOutPrs.int    ; Vault City Outsider Prisoner (Generic)
{489}{}{囚犯}                           # VCCitPrs.int    ; Vault City Citizen Prisoner (Generic)
{490}{}{公民}                           # VCGenFam.int    ; Vault City Generic Family
{491}{}{阿曼提斯的助手}                 # VCAmAid.int     ; Vault City Amenities Aid
{492}{}{接應衛兵}                       # GCRDesk.int     ; Gecko Reactor Desk Guard
{493}{}{僵屍工人}                       # GCRGhoul.int    ; Gecko Reactor Ghoul Worker
{494}{}{發光的人}                       # GCRGlow.int     ; Gecko Glowing One
{495}{}{僵屍衛兵}                       # GCRGuard.int    ; Gecko Red Door Guard
{496}{}{機器人}                         # GCRobot.int     ; Gecko Reactor Robot
{497}{}{僵屍}                           # GCFolk.int      ; Gecko Townsfolk
{498}{}{朝拜者}                         # GCWorshp.int    ; Gecko Worshippers
{499}{}{哈歐}                           # GCHarold.int    ; Harold in Gecko
{500}{}{警衛}                           # GCPACOff.int    ; Gecko Powered Armor Com Officer
{501}{}{多多}                           # SCToto.int      ; Toto hlper bot in NCR 1
{502}{}{德露西}                         # SCDoroth.int    ; Dorothy Repair chick in NCR 1
{503}{}{鎮民}                           # ncPerson.int    ; New Reno Generic Townsperson/Citizen
{504}{}{僵屍衛兵}                       # GCYGuard.int    ; Gecko Yellow Door Guard
{505}{}{僵屍衛兵}                       # GCGuard.int     ; Gecko Generic Guard
{506}{}{剛德}                           # SCGond.int      ; Ranger Guard, NCR 1
{507}{}{杜普}                           # SCDuppo.int     ; Stockman's yard store owner
{508}{}{東西}                           # SIdtbl.int      ; Duppo's tables in shop
{509}{}{包伯}                           # SCsalbob.int    ; Salt Beef Bob NCR 3
{510}{}{賭場侍女}                       # ziDceGrl.int    ; Generic Casino Girl with Dice Game
{511}{}{賭場侍女}                       # niDceGrl.int    ; New Reno Casino Girl with Dice Game
{512}{}{魔幻的八號球}                   # zi8Ball.int     ; EPA Magic 8 Ball
{513}{}{雙頭牛}                         # ncAngBra.int    ; New Reno Angry Brahmin
{514}{}{吃角子老虎}                     # niMcGSlt.int    ; New Reno McGee's Slot Machine
{515}{}{老人麥可基}                     # ncMcGee.int     ; New Reno Old Man (Bobby) McGee
{516}{}{三張牌定勝負}                   # nc3Monte.int    ; New Reno Three Card Monte
{517}{}{阿爾基南}                       # ncAlgern.int    ; New Reno Algernon
{518}{}{比爾}                           # ncBill .int     ; New Reno Bill (Trees Lounge)
{519}{}{保鑣}                           # ncBisGrd.int    ; New Reno Bishop's Bodyguards
{520}{}{約翰彼希}                       # ncBishop.int    ; New Reno John Bishop
{521}{}{賭場機器}                       # niCasMac.int    ; New Reno Casino Machine
{522}{}{機器行員工}                     # ncChpBoy.int    ; New Reno Chop Shop Boys
{523}{}{克里斯．萊特}                   # ncChrWri.int    ; New Reno Chris Wright
{524}{}{寇弟}                           # ncCody .int     ; New Reno Cody
{525}{}{克里西根兄弟}                   # ncCorBro.int    ; New Reno Corsican Bothers
{526}{}{愛爾及}                         # ncEldrid.int    ; New Reno Eldridge
{527}{}{依希．萊特}                     # ncEthWri.int    ; New Reno Ethyl Wright
{528}{}{塔里神父}                       # ncFTully.int    ; New Reno Father Tully
{529}{}{可可迪多}                       # ncHumper.int    ; New Reno HumperdumperDIDO
{530}{}{基蘇．莫丁諾}                   # ncLilJes.int    ; New Reno Lil' Jesus Mordino
{531}{}{吉米Ｊ}                         # ncJimmyJ.int    ; New Reno Jagged Jimmy J
{532}{}{基斯．萊特}                     # ncKeiWri.int    ; New Reno Keith Wright
{533}{}{理．安．彼希}                   # ncLABish.int    ; New Reno Lee Anne Bishop
{534}{}{漂亮男孩洛依德}                 # ncLloyd.int     ; New Reno Pretty Boy Lloyd
{535}{}{梅森}                           # ncMason.int     ; New Reno Mason
{536}{}{衛兵}                           # ncMyrGrd.int    ; New Reno Myron's Guards
{537}{}{麥朗}                           # nhMyron.int     ; New Reno Myron (Talking Head)
{538}{}{妮基}                           # ncNikki.int     ; New Reno Darlin' Nikki
{539}{}{奧薇爾．萊特}                   # ncOrvill.int    ; New Reno Orville Wright
{540}{}{老闆}                           # ncPitBos.int    ; New Reno Generic Pit Boss
{541}{}{洛尼司可}                       # ncRenesc.int    ; New Reno Renesco the Rocket-Man
{542}{}{研究員}                         # ncResear.int    ; New Reno Stables Researcher
{543}{}{沙爾瓦多老大}                   # ncSalvat.int    ; New Reno Boss Salvatore
{544}{}{史度特．理特}                   # ncStuLit.int    ; New Reno Stuart Little (Agent)
{545}{}{Ｔ雷}                           # ncTRay .int     ; New Reno T-Ray
{546}{}{婊子}                           # ncBitch.int     ; New Reno Corsican Brothers Bitches
{547}{}{萊特的小孩}                     # ncWriPly.int    ; New Reno Wright Children Playing
{548}{}{新加州共合國警察}               # SCCop.int       ; NCR cop
{549}{}{奧斯瓦德}                       # SCOswald.int    ; Raider Oswald captive NCR 1
{550}{}{達士地}                         # SCDusty.int     ; Dusty bartender in NCR 1
{551}{}{朱爾斯}                         # ncJules.int     ; New Reno Jules
{552}{}{凱蒂小姐}                       # ncKitty.int     ; New Reno Miss Kitty
{553}{}{酒保}                           # ncBarten.int    ; New Reno Bartender
{554}{}{卡爾副手}                       # SCKarl.int      ; NCR Deputy
{555}{}{牢門}                           # SIKdoor.int     ; NCR Cell door
{556}{}{大莫丁諾}                       # ncBigJes.int    ; New Reno Big Jesus Mordino
{557}{}{荷斯}                           # SCHoss.int      ; Hoss, bully NCR 1 map
{558}{}{變型糖漿}                       # SIMserum.int    ; Mutagenic Serum
{559}{}{盒子}                           # niSalBox.int    ; New Reno Salvatore Bartender Shop Inventory
{560}{}{盒子}                           # niMorBox.int    ; New Reno Mordino Bartender Shop Inventory
{561}{}{盒子}                           # niBisBox.int    ; New Reno Bishop Bartender Shop Inventory
{562}{}{盒子}                           # niTmpBox.int    ; New Reno Personal Inventory Swap Box
{563}{}{朱伯利醫生}                     # SCDocJub.int    ; Doctor Jubilee NCR Map 1
{564}{}{門}                             # GSYDoor.int     ; Yellow Door in Gecko Reactor
{565}{}{門}                             # GSRDoor.int     ; Red Door in Gecko Reactor
{566}{}{書櫃}                           # SIdshelf.int    ; Bookshelf for the Doc NCR 1
{567}{}{杜門警長}                       # SCsherif.int    ; Sheriff in NCR map 1
{568}{}{依麗莎}                         # SCElise.int     ; Elise in NCR map 1 ranger leader chick
{569}{}{牧場工人}                       # SCwrHand.int    ; Westin Ranch Hand NCR 3
{570}{}{菲利}                           # SCFelix.int     ; Westin's forman on NCR 3
{571}{}{衛斯丁}                         # SCWestin.int    ; Westin big dude on NCR 3
{572}{}{藍多}                           # SCRondo.int     ; Rondo Ranger NCR 1
{573}{}{機器狗}                         # SCRobo.int      ; Robodog NCR 1
{574}{}{樓梯}　　　　　                 # NIBissta.int    ; New Reno Bishop's stairs
{575}{}{哈爾}                           # SCHal.int       ; Hal, Drive Leader
{576}{}{甘德}                           # SCGunthr.int    ; Gunther Tandi's assistant NCR 2
{577}{}{雙頭牛}                         # ECCrtBra.int    ; Random Encounter Brahmin for carts
{578}{}{沙漠商隊首領}                   # ECCvnMst.int    ; Random Encounter Caravan Master
{579}{}{沙漠商隊駕駛}                   # ECCvnDrv.int    ; Random Encounter Caravan Driver
{580}{}{沙漠商隊衛兵}                   # ECCvnGrd.int    ; Random Encounter Caravan Guard
{581}{}{歹徒}                           # ECRadLdr.int    ; Random Encounter Raider Leader
{582}{}{幫派份子}                       # ECMobstr.int    ; Random Encounter Mobster (Outside New Reno)
{583}{}{獵人}                           # ECHntLdr.int    ; Random Encoutner Hunting Party Leader
{584}{}{獵人}                           # ECHunter.int    ; Random Encounter Hunting Party
{585}{}{巡警}                           # ECRanger.int    ; Random Encounter NCR Rangers (Patrol)
{586}{}{傭兵}                           # ECMercs.int     ; Random Encounter Mercenaries
{587}{}{傭兵}                           # ECMrcLdr.int    ; Random Encounter Mercenary Leader
{588}{}{歹徒}                           # ECRadGrp.int    ; Random Encounter Raider Party
{589}{}{沙漠商隊駕駛}                   # ECRndDrv.int    ; Random Encounter Other Caravan Driver
{590}{}{沙漠商隊衛兵}                   # ECRndGrd.int    ; Random Encounter Other Caravan Guard
{591}{}{巡邏兵}                         # ECVltPat.int    ; Random Encounter Vault City Patrols
{592}{}{巡邏兵隊長}                     # ECVltCpt.int    ; Random Encounter Vault City Patrol Capt.
{593}{}{農夫}                           # ECFarmer.int    ; Random Encounter Farmer
{594}{}{雙頭牛}                         # ECBraHrd.int    ; Random Encounter Brahmin Herd
{595}{}{雙頭牛}                         # ECLedBra.int    ; Random Encounter Lead Brahmin
{596}{}{旅行者}                         # ECTrvlr.int     ; Random Encounter Traveler
{597}{}{巡邏兵}                         # ECGhlPat.int    ; Random Encounter Ghoul Patrol
{598}{}{巡邏兵隊長}                     # ECGhlCpt.int    ; Random Encounter Ghoul Patrol Capt.
{599}{}{巡邏兵}                         # ECMutPat.int    ; Random Encounter Mutant Patrol
{600}{}{巡邏兵隊長}                     # ECMutCpt.int    ; Random Encounter Mutant Patrol Capt.
{601}{}{雙頭牛駕駛}                     # ECBraDrv.int    ; Random Encounter Brahmin Driver
{602}{}{偷牛賊}　                       # ECBraRst.int    ; Random Encounter Brahmin Rustler
{603}{}{流浪漢}                         # ECSquatr.int    ; Random Encounter Squatters
{604}{}{廢奴主義者}                     # ECAbolst.int    ; Random Encounter Abolitionist
{605}{}{私販酒者}                       # ECMonShn.int    ; Random Encounter Moonshine Runner
{606}{}{超級變種人}                     # ECRogMut.int    ; Random Encounter Rogue Super Mutants
{607}{}{漁夫}                           # ECFshrmn.int    ; Random Encounter Fisherman
{608}{}{奴隸販子}                       # ECSlaver.int    ; Random Encounter Slaver
{609}{}{蜥蝪獵人}                       # ECTrappr.int    ; Random Encounter Trapper
{610}{}{卡洛森的小孩}                   # SCCarkid.int    ; Carlson's kid NCR map 2
{611}{}{卡洛森}                         # SCCarlsn.int    ; Carlson NCR 2
{612}{}{}                               # Animfrv.int     ; Animate forever
{613}{}{傑克}                           # SCOfjack.int    ; Officer Jack NCR 1
{614}{}{受啟蒙的人}                     # SCEnlOne.int    ; The Enlightened One NCR 1
{615}{}{門}                             # diDoor.int      ; Den Auto Closing Door
{616}{}{電腦}                           # GsTerm.int      ; Gecko robot control terminal
{617}{}{雙頭牛}                         # SCBrahmn.int    ; NCR Map 4 Brahmin.
{618}{}{死亡爪}                         # SCDthcla.int    ; NCR Map 4 Deathclaw.
{619}{}{出口}                           # SIExit.int      ; NCR Map 4 Exit Grid control
{620}{}{電腦}                           # SSComp.int      ; NCR Map 1 computer terminal that blows up
{621}{}{費爾格斯}                       # SCFergus.int    ; NCR Map 2
{622}{}{愛瑞兒}                         # OCAriel.int     ; Vault 13 Ariel
{623}{}{菲妮美}                         # RCFannie.int    ; Fannie Mae the hooker in Redding
{624}{}{電腦控制臺}                     # OCComptr.int    ; Computer terminal in Vault 13
{625}{}{達莉雅}                         # OCDalia.int     ; Dalia in Vault 13
{626}{}{達爾}                           # OCDar.int       ; Dar Deathclaw guard Vault 13
{627}{}{達夫}                           # OCDave.int      ; Dave NPC in Vault 13
{628}{}{格登}                           # OCGordon.int    ; Gordon the shrine temple dude
{629}{}{倒閉標誌}                       # ziClosed.int    ; Generic "Out of Business" signs
{630}{}{反應爐控制機器}                 # gsReactr.int    ; Script to animate reactor
{631}{}{吉米}                           # OCJimmy.int     ; Jimmy guy in computer room Vault 13
{632}{}{約瑟夫}                         # OCJoseph.int    ; The Doctor in Vault 13
{633}{}{麥特}                           # OCMatt.int      ; Matt prisonner in Vault 13
{634}{}{}                               # RCFitRat.int    ; Redding Fighting Molerats
{635}{}{地圖}                           # RedMEnt.int     ; Redding Mine Entrance Map Script
{636}{}{第１３號避難所地圖}             # vault13.int     ; Vault13 map script
{637}{}{珊蒂}                           # OCSandy.int     ; Sandy Vault 13 child.
{638}{}{盒子}                           # ziTmpBox.int    ; Generic Temporary swap box
{639}{}{史恩}                           # OCThearn.int    ; Vault 13 Guard Thearn.
{640}{}{盒子}                           # miGriBox.int    ; Modoc Grisham Merchant box
{641}{}{盒子}                           # miJoBox.int     ; Modoc Jo Merchant box
{642}{}{比爾地斯}                       # OCValdis.int    ; Valdis guard in Vault 13
{643}{}{電腦控制台}                     # OSvdrcmp.int    ; Door computer vault 13 entrance
{644}{}{鐵鎖櫃}                         # OILocker.int    ; Metal locker in Vault 13
{645}{}{鎖櫃}                           # OIftlkr.int     ; Footlocker in Vault 13
{646}{}{死亡爪衛兵}                     # OCgrunt.int     ; Generic Vault 13 Deathclaw guard
{647}{}{革力士}                       # OCGoris.int     ; Goris possible party NPC vault 13
{648}{}{盒子}                           # miBalBox.int    ; Modoc Balthas Merchant box
{649}{}{鐵鎖櫃}                         # siLocker.int    ; Guard's lockers in NCR 1
{650}{}{作弊者}                         # Cheater.int     ; Cheater Character
{651}{}{第１５號避難所地圖}             # vault15.int     ; Vault 15 map script
{652}{}{費爾}                           # bcPhil.int      ; Phil the secret vault 15 entrance guard
{653}{}{比爾}                           # bcBill.int      ; Bill in Vault 15 Entrance
{654}{}{屠夫}                           # mcButchr.int    ; Slaughter house guys in Modoc
{655}{}{達莉雅}                         # bcDalia.int     ; Guard who guards a trail and shows up in v13
{656}{}{約翰}                           # bcJohn.int      ; Vault 15 guy entrance
{657}{}{瓊斯}                           # BCJones.int     ; Vault 15 doctor
{658}{}{卡拉}                           # BCKarla.int     ; Karla Vault 15 guard.
{659}{}{第１５號避難所秘密入口地圖}     # V15sent.int     ; Vault 15 secret entrance map
{660}{}{麗蓓嘉}                         # BCRebecc.int    ; Vault 15 Rebecca
{661}{}{門}                             # miDoor.int      ; Modoc Doors
{662}{}{死亡爪}                         # mcDthClw.int    ; Modoc Rose's "Chicken"
{663}{}{蘿伯可}                         # bcRobert.int    ; Roberta Vault 15 Entrace
{664}{}{莎拉}                           # bcSara.int      ; Sara vault 15 Entrance
{665}{}{希克}                           # bcZeke.int      ; Zeke vault 15 Entrance mayor dude
{666}{}{雙頭牛}                         # bcBrahmn.int    ; Generic Brahmin in Vault15 Entrance
{667}{}{木門}                           # BiEntDr.int     ; Trapped Vault15 entrance door
{668}{}{可莉西}                         # BCCrissy.int    ; Crissy, Rebecca's daughter
{669}{}{達里安}                         # BCDarion.int    ; Big bad dude in Vault 15
{670}{}{達里安的衛兵}                   # BCDargrd.int    ; Darion's guard in Vault 15
{671}{}{達里安的狗}                     # BCDardog.int    ; Darion's dog in Vault 15
{672}{}{蓋西迪}                         # VCCasidy.int    ; Cassidy the  bar person in Vault City
{673}{}{水井}                           # miWell.int      ; Modoc Well
{674}{}{地鼠}                           # mcMolRat.int    ; Modoc Shitter Mole Rat
{675}{}{雙頭牛肉}                       # miBraMea.int    ; Modoc Brahmin Chunks
{676}{}{雙頭牛}                         # mcKilBra.int    ; Modoc Slaughterhouse brahmin
{677}{}{電梯門}                         # bsElev.int      ; Elevator door in V15sent
{678}{}{狗}                             # mcKilDog.int    ; Modoc Dog that hangs out at the slaughter house
{679}{}{老鼠}                           # mcRat.int       ; Modoc Garden Rat
{680}{}{陽光點}                         # ziSunSpt.int    ; Generic Sun Spot
{681}{}{貝絲}                           # mcBess.int      ; Modoc Bess the Brahmin
{682}{}{盒子}                           # miJkyBox.int    ; Modoc Jerky box
{683}{}{骰子莊家}                       # zcCrpDel.int    ; Craps Dealer
{684}{}{第１５號避難所衛兵}             # bcGenGrd.int    ; Vault 15 Khan Guard
{685}{}{溶渣}                           # mcSlag.int      ; Modoc Generic Slag
{686}{}{地毯}                           # mtRug.int       ; Modoc Spacial Script for Rug
{687}{}{小孩}                           # mcChild.int     ; Modoc Child
{688}{}{愛琳}                           # hcAileen.int    ; Aileen in Broken Hills
{689}{}{衛兵}                           # hcBnkGrd.int    ; Bank Guard in Broken Hills
{690}{}{荷里代醫生}                     # hcDoc.int       ; Doc in Broken Hills
{691}{}{追從者}                         # hcencha.int     ; Henchman A in Broken Hills
{692}{}{追從者}                         # hcenchb.int     ; Henchman B in Broken Hills
{693}{}{女人}                           # hcfemale.int    ; Female in Broken Hills
{694}{}{法藍西斯}                       # hcFranci.int    ; Francis in Broken Hills
{695}{}{法蘭克}                         # hcFrank.int     ; Frank in Broken Hills
{696}{}{僵屍}                           # hcGhoul.int     ; Ghoul in Broken Hills
{697}{}{麗莎}                           # hcLiz.int       ; Liz in Broken Hills
{698}{}{男人}                           # hcmale.int      ; Male in Broken Hills
{699}{}{曼森}                           # hcManson.int    ; Manson in Broken Hills
{700}{}{馬可世}                         # hcMarcus.int    ; Marcus in Broken Hills
{701}{}{礦工}                           # hcMiners.int    ; Miners in Broken Hills
{702}{}{變種人}                         # hcMutant.int    ; Mutant in Broken Hills
{703}{}{比爾}                           # hcOutfit.int    ; Outfitter in Broken Hills
{704}{}{費爾}                           # hcPhil.int      ; Phil the bartender in Broken Hills
{705}{}{史提夫}                         # hcSteve.int     ; Steve in Broken Hills
{706}{}{上司}                           # hcSuper.int     ; Supervisor in Broken Hills
{707}{}{賽斯}                           # hcZaius.int     ; Zaius in Broken Hills
{708}{}{傑克伯}                         # hcJacob.int     ; Jacob in Broken Hills
{709}{}{化學實驗用品}                   # hchems.int      ; Chemistry Set in Broken Hills
{710}{}{工具}                           # miGstPrp.int    ; Modoc Ghost Farm Prop
{711}{}{門}                             # bssdor1.int     ; Shack doors on V15sEnt map
{712}{}{電腦}                           # BSComp1.int     ; Library Computer Vault 15
{713}{}{查德}                           # hcchad.int      ; Chad from Broken Hills
{714}{}{胞子植物}                       # ECPlant.int     ; Random Encounter Spore Plant
{715}{}{蜥蝪}                           # ECGecko.int     ; Random Encounter Gecko
{716}{}{毒蠍子}                         # ECScorp.int     ; Random Encounter Scorpions
{717}{}{老鼠}                           # ECRat.int       ; Random Encounter Rats
{718}{}{戰士}                           # ECWarPty.int    ; Random Encounter War Party
{719}{}{食人族}                         # ECCanibl.int    ; Random Encounter Cannibals
{720}{}{被逐出的人}                     # ECOutCst.int    ; Random Encounter Outcasts
{721}{}{聖人}                           # ECHlyPpl.int    ; Random Encounter Holy People
{722}{}{遊牧者}                         # ECNomad.int     ; Random Encounter Nomads
{723}{}{無家可歸的人}                   # ECHomles.int    ; Random Encounter Homeless
{724}{}{土匪}                           # ECBandit.int    ; Random Encounter Bandit
{725}{}{強盜}                           # ECRobber.int    ; Random Encounter Robber
{726}{}{攔路強盜}                       # ECHiwymn.int    ; Random Encounter Highwaymen
{727}{}{奴隸販子}                         # ECSlvRun.int    ; Random Encounter Slavers on a Slave Run
{728}{}{奴隸}                           # ECSlave.int     ; Random Encounter Slaves
{729}{}{人}                             # ECRavPty.int    ; Random Encounter Rave Party
{730}{}{螳螂}                           # ECMantis.int    ; Random Encounter Mantis
{731}{}{雙頭牛}                         # ECBrahmn.int    ; Random Encounter Brahmin
{732}{}{狗}                             # ECWldDog.int    ; Random Encounter Wild Dogs
{733}{}{電腦}                           # BSComp2.int     ; Darion's computer terminal Vault15
{734}{}{電腦}                           # BSComp3.int     ; Force field computer terminal
{735}{}{電腦控制台}                     # BSComp4.int     ; Force Field control computer by entrance Vault 15
{736}{}{電腦}                           # BSComp5.int     ; Computer at the Power area. Vault 15
{737}{}{發電機}                         # BSPower.int     ; Power Generator in Vault 15
{738}{}{力場}                           # BSField.int     ; Force Field in Vault 15
{739}{}{平民}                           # mcPeasan.int    ; Modoc Peasant Person
{740}{}{發射器}                         # bsEmtr.int      ; Emitter in Vault 15
{741}{}{避難所門}                       # osv13dr.int     ; Vault 13 Door
{742}{}{安全門}                         # osDoor1.int     ; Vault 13 Door that shows deathclaws
{743}{}{遇到貝絲}                       # rndBess.int     ; Random Encounter for Bess outside of modoc
{744}{}{貝絲}                           # ECBess.int      ; Bess in Bess's Encounter (she's dead jim)
{745}{}{雙頭牛}                         # ECBesCow.int    ; One of the Brahmin in Bess's herd
{746}{}{安琪拉．彼希}                   # ncAngBis.int    ; New Reno Angela Bishop
{747}{}{湯米}                           # ncTommy.int     ; New Reno Tommy the Balls (YEAH! OUR HERO)
{748}{}{保險箱}                         # niABisSf.int    ; New Reno Angela Bishop's Safe
{749}{}{保險箱}                         # niMrBSf.int     ; New Reno Mr. Bishop's Safe
{750}{}{保險箱}                         # niMrsBSf.int    ; New Reno Mrs. Bishop's Safe
{751}{}{保險箱}                         # niOWriSf.int    ; New Reno Orville Wright's Safe
{752}{}{墳墓}                           # niPriGrv.int    ; New Reno Pritchard's Grave
{753}{}{梳妝臺}                         # niWridrs.int    ; New Reno Richard Wright's Dresser
{754}{}{墳墓}                           # niWriGrv.int    ; New Reno Righard Wright's Grave
{755}{}{蒸餾器}                         # niWriSti.int    ; New Reno Wright Stills
{756}{}{洛米洛茲}                       # ncRamire.int    ; New Reno Ramirez
{757}{}{山洞１亂數地圖}                 # cave01.int      ; Cave 1 Random Encounter Map
{758}{}{盒子}                           # niRenBox.int    ; New Reno Renesco Box
{759}{}{門}                             # niDoor.int      ; New Reno Door
{760}{}{山洞２亂數地圖}                 # cave02.int      ; Cave 2 Random Encounter Map
{761}{}{山洞３亂數地圖}                 # cave03.int      ; Cave 3 Random Encounter Map
{762}{}{山洞４亂數地圖}                 # cave04.int      ; Cave 4 Random Encounter Map
{763}{}{山洞２亂數地圖}                 # cave02.int      ; Cave 2 Random Encounter Map
{764}{}{門}                             # VIEntDor.int    ; Vault City Entrance Door
{765}{}{地圖}                           # VCtyDwtn.int    ; Vault City Downtown Map script
{766}{}{陷阱門}                         # miTrpDor.int    ; Modoc Ghost Farm Trap Door
{767}{}{上鎖的箱子}                     # Hilbox.int      ; Broken Hills Liz inventory box
{768}{}{房間}                           # ntLydRom.int    ; New Reno Lloyd Room
{769}{}{湯姆士．摩爾}                   # VCMoore.int     ; Thomas Moore from Vault City
{770}{}{門}                             # ZILckDor.int    ; Generic Locked Door (-20)
{771}{}{鎖櫃}                           # niLydBox.int    ; New Reno Lloyd's Loot Box
{772}{}{地下水道通道}                   # niManhol.int    ; New Reno Manhole to Lloyd's Loot
{773}{}{墳墓}                           # niLydGrv.int    ; New Reno Lloyd's Loot Grave
{774}{}{補給品衛兵}                     # VCSupGrd.int    ; Vault City Supply Guard Martin
{775}{}{地圖}                           # broken1.int     ; Map Script for Broken Hills Map 1
{776}{}{地圖}                           # rndexcow.int    ; Map Script for Low Luck encounter
{777}{}{瘋牛}                           # eccowbmb.int    ; The cows that blow
{778}{}{漢克斯威爾}                     # RCHakes.int     ; Hakeswill from Redding
{779}{}{瑞丁城市中心}                   # REDDown.int     ; Redding Downtown map script
{780}{}{地圖}                           # BHRndDst.int    ; Broken Hills Caravan Desert Map
{781}{}{地圖}                           # BHRndMtn.int    ; Broken Hills Caravan Mountain Map
{782}{}{盧}                             # RCLou.int       ; Lou from Redding
{783}{}{亞瑟}                           # ECArthur.int    ; Arthur the leader of the Special Encounter knights
{784}{}{羅賓}                           # ECRobin.int     ; Robin one of the Knights with Arthur
{785}{}{班地梅爾}                       # ECBedemi.int    ; Bedemir one of the Knights with Arthur
{786}{}{藍瑟安特公爵}                   # ECSirLau.int    ; Sir Launcelot one of the Knights with Arthur
{787}{}{加拉韓德}                       # ECGalaha.int    ; Galahad one of the knights iwth Arthur
{788}{}{班．偉德}                       # RCWade.int      ; Ben Wade from Radding
{789}{}{阿沙巴士卡．狄克}               # RCDick.int      ; Athabaska Dick from Redding
{790}{}{寡婦羅妮}                       # RCRooney.int    ; Widow Rooney from Redding
{791}{}{鎮民}                           # RCGenPes.int    ; Generic Townsperson in Redding
{792}{}{史丹威爾}                       # RCStanwl.int    ; Stannwell from Redding
{793}{}{沙文力}                         # RCSavine.int    ; Savinelli from Redding
{794}{}{馬琪}                           # RCMarge.int     ; Marge LeBarge from Redding
{795}{}{馬德嘉士琪夫人}                 # RCModjes.int    ; Madam Modjeska from Redding
{796}{}{詹姆士．哈菲}                   # RCHoffy.int     ; James Hoffy, Caravan Master for Redding
{797}{}{地圖}                           # Rndholy1.int    ; Random Encounter Holy Knights 1 map
{798}{}{派西}                           # ECPatsy.int     ; Arthur's horse HOLY 1 encounter
{799}{}{康克地}                         # ECConcor.int    ; Concord Launcelot's horse.
{800}{}{艾力克}                         # ECEric.int      ; Robin's horse
{801}{}{約翰}                           # ECJohn.int      ; Bedemir's horse
{802}{}{約瑟}                           # ECJoshua.int    ; Joshua Robin's minstrel
{803}{}{拉德}                           # miLadder.int    ; Modoc Shitter Ladder
{804}{}{大頭}　　　　　                 # ecBHead.int     ; Big Head special encounter
{805}{}{黑色英雄}                       # ecBlkHro.int    ; Black Hero model
{806}{}{紅色女英雄}                     # ecRedHro.int    ; Red Heroine model
{807}{}{背景}                           # ecSet.int       ; Set in Cafe of Broken Dreams
{808}{}{坦蒂}                           # ecTandi.int     ; Tandi in Cafe of " "
{809}{}{白色英雄}                       # ecWhro1.int     ; White Hero Model 1 " " "
{810}{}{白色英雄}                       # ecWhro2.int     ; White Hero Model 2 " " "
{811}{}{白色女英雄}                     # ecWheon1.int    ; White Heroine Model 1
{812}{}{盒子}                           # NiJulBox.int    ; New Reno Jules Shop Inventory Box
{813}{}{盒子}                           # niEldBox.int    ; New Reno Eldridge Shop Box
{814}{}{盒子}                           # niEldBx2.int    ; New Reno Eldridge Shop Box (For Made Men)
{815}{}{地圖}                           # rndholy2.int    ; Hi-Luck random Holy knight encounter 2
{816}{}{老鼠}                           # ECVorRat.int    ; Vorpal Rat for Holy Knight 2
{817}{}{狗}                             # ECPDog.int      ; Pariah Dog... not good to have following you around
{818}{}{演習上校}                       # CCDrill.int     ; Drill Seargant in Colusa/Nevarro
{819}{}{衛兵}                           # CCGuard.int     ; Guard in Colusa/Nevarro
{820}{}{技術人員}                       # CCTech.int      ; Technician in Colusa/Nevarro
{821}{}{指揮官}                         # CCMandr.int     ; Commander in Colusa Nevarro
{822}{}{基斯}                           # CCChris.int     ; Chris the gas station attendant in Colusa
{823}{}{房間主管}                       # CCMaster.int    ; Quarter Master in Colusa/Nevarro
{824}{}{衛兵}                           # CCGGuard.int    ; Gate Guard in Colusa/Nevarro
{825}{}{墳墓}                           # ntLydGrv.int    ; New Reno Lloyd's Loot Grave (Spacial Script)
{826}{}{車}                             # ntCar1.int      ; New Reno Stolen Car Seed Spacial 1
{827}{}{車}                             # ntCar2.int      ; New Reno Stolen Car Seed Spacial 2
{828}{}{墳墓}                           # niMorGrv.int    ; New Reno Mordino Stash Grave
{829}{}{穿長袍的人物}                   # EcBridge.int    ; Bridge guy special encounter
{830}{}{牲口買家}                       # SCdrvpay.int    ; Cattle drive from NCR to redding.
{831}{}{地圖}                           # RndBridg.int    ; Random Bridge encounter
{832}{}{神秘的陌生人}                   # ECMstStr.int    ; Mysterious Stranger
{833}{}{瘋牛}                           # ECgcwbmb.int    ; Generic Cow bomb
{834}{}{}                               # ECYakuza.int    ; Random Encounter Yakuza
{835}{}{}                               # ECWilder.int    ; Random Encounter Wilder
{836}{}{狗}                             # ncWriDog.int    ; New Reno Wright Dog
{837}{}{盒子}                           # niRamBox.int    ; New Reno Box to be delivered to Ramirez
{838}{}{}                               # ECUniPat.int    ; Unity Patrol Random Encounter
{839}{}{}                               # ECTravlr.int    ; Random Encounter Travler
{840}{}{煙}                             # KtSmoke.int     ; displays message about smoke smell in Duntons
{841}{}{商人}                           # ECTrader.int    ; Random Encounter Trader
{842}{}{僵屍}                           # ECScaven.int    ; Random Encounter Scavenger
{843}{}{商人}                           # FCMercha.int    ; San Fran Air bag merchant
{844}{}{平民}                           # FCBadPea.int    ; San Fran Bad Peasants
{845}{}{阿羅由神殿}                     # ARTemple.int    ; Arroyo Temple map script
{846}{}{碼頭工人}                       # FCDokWrk.int    ; San Fran Dock Worker
{847}{}{平民}                           # FCGudPea.int    ; San Fran Good Peasants
{848}{}{始族衛兵}                     # FCShiGrd.int    ; San Fran Shi Guard
{849}{}{戰士}                           # ACTemVil.int    ; Temple challenge person
{850}{}{門}                             # AITemDor.int    ; Temple doors that lock at the challenge
{851}{}{克林特}                         # ACKlint.int     ; Klint the guardian of the temple exit
{852}{}{穀物}                           # AICrops.int     ; Crops that die after a period of time
{853}{}{始族科技}                     # FCslabte.int    ; San Fran Shi Lab techs
{854}{}{小孩}                           # FCSkids.int     ; San Fran Shi Kids
{855}{}{僵屍}                           # GCWander.int    ; wandering ghouls in Gecko
{856}{}{方博士}                         # FCDrFung.int    ; San Fran Dr Fung
{857}{}{交爾}                           # OCJul.int       ; Vault 13 Denmother Guard
{858}{}{科瑞斯}                         # OCKerith.int    ; Vault 13 Den Mother
{859}{}{箱子}                           # AITemCst.int    ; Temple Chest to hold the players things
{860}{}{僵屍}                           # GCRGhul.int     ; Reactor ghoul that doesn't move
{861}{}{}                               # ECRaiBow.int    ; Random Encounter Gays
{862}{}{}                               # ECMstAmy.int    ; Random Encounter Master's Army
{863}{}{採礦者}                         # ECProspe.int    ; Random Encounter Prospector
{864}{}{}                               # ECPrsGng.int    ; Random Encounter Press Gang
{865}{}{遊牧民族首領}                   # ECNomChf.int    ; Random Encounter Nomad Chief
{866}{}{哈伯教}                         # ECElRon.int     ; Hubologist Patrol
{867}{}{瘋子}                           # ECCrazy.int     ; Crazies from Random Encounter
{868}{}{騙子}                           # ECClmJmp.int    ; Random Encounter Claim Jumpers
{869}{}{食人族}                         # ECCanbal.int    ; Random Encounter Cannibals
{870}{}{遊牧民族巫師}                   # ECNomSha.int    ; Random Encounter Nomad Shamon
{871}{}{掠劫者}                         # ECMaradr.int    ; Random Encounter Marauder
{872}{}{惡棍}                           # ECRogue.int     ; Random Encounter Rogue
{873}{}{隱士}                           # ECHermit.int    ; Random Encounter Hermit
{874}{}{}                               # ECGangs.int     ; Random Encounter Gangs
{875}{}{商隊首領}                       # ECMstKla.int    ; Random Encounter Klamath Caravan Master
{876}{}{商隊首領}                       # ECMstDen.int    ; Random Encounter Den Caravan Master
{877}{}{商隊首領}                       # ECMstNew.int    ; Random Encounter New Reno Caravan Master
{878}{}{商隊首領}                       # ECMstRed.int    ; Random Encounter Redding Caravan Master
{879}{}{商隊首領}                       # ECMstBro.int    ; Random Encounter Broken Hills Caravan Master
{880}{}{商隊首領}                       # ECMstGec.int    ; Random Encounter Gecko Caravan Master
{881}{}{商隊首領}                       # ECMstSan.int    ; Random Encounter San Fran Caravan Master
{882}{}{商隊首領}                       # ECMstNCR.int    ; Random Encounter NCR Caravan Master
{883}{}{商隊首領}                       # ECMstV15.int    ; Random Encounter Vault 15 Caravan Master
{884}{}{農夫的老婆}                     # ECFrmWfe.int    ; Random Encounter Farmer's wife
{885}{}{農夫的小孩}                     # ECFrmKid.int    ; Random Encounter Farmer's Kid
{886}{}{農場主人}                       # ECHomest.int    ; Random Encounter Homesteader
{887}{}{農場女主人}                     # ECHomwfe.int    ; Random Encounter Homesteader's Wife
{888}{}{農場主人的小孩}                 # ECHomKid.int    ; Random Encounter Homesteader's Kid
{889}{}{商隊首領}                       # ECMstVC.int     ; Random Encounter Vault City Caravan Master
{890}{}{}                               # ECAlien.int     ; Random Encounter Alien
{891}{}{}                               # ECDthclw.int    ; Random Encounter Deathclaws
{892}{}{}                               # ECFloatr.int    ; Random Encounter Floater
{893}{}{}                               # ECCentur.int    ; Random Encounter Centaurs
{894}{}{英克雷軍巡邏員}                 # ECElvPat.int    ; Random Encounter Enclave Patrol
{895}{}{隊長}                           # icMrcCpt.int    ; Raiders Merc Captain
{896}{}{歹徒}                           # icMerc.int      ; Raiders Merc
{897}{}{"影者"}                         # icScout.int     ; Raiders Scout
{898}{}{保險箱}                         # iiSafe.int      ; Raiders Safe
{899}{}{}                               # raiders1.int    ; Raiders 1 Enterance
{900}{}{}                               # raiders2.int    ; Raiders 2 Caves
{901}{}{}                               # HSCellDr.int    ; Broken Hills bank/jail door
{902}{}{盒子}                           # niTRyBox.int    ; New Reno Chop Shop T-Ray Box
{903}{}{理察森總統}                     # qhPrzRch.int    ; Enclave President Richardson talking head.
{904}{}{豪衛慈}                         # WIHowitz.int    ; Howitzer in the Sierra Base
{905}{}{門}                             # WIEntDor.int    ; Entrance to Sierra Base Door
{906}{}{死亡爪幼蟲}                     # OCBabDth.int    ; Baby Deathclaws in Vault 13
{907}{}{丹}                             # RCMcGrew.int    ; Dangerous Dan McGrew from redding
{908}{}{強森}                           # RCDrJohn.int    ; Painless Doc Johnson (breaks Jet)
{909}{}{馬力安警長}                     # RCMarion.int    ; Sheriff Earl Marion
{910}{}{阿思寇提市長}                   # RCAscort.int    ; Mayor Ascorti of Redding
{911}{}{諾丁}                           # RCNord.int      ; Nording, the payoff man for Stanwell
{912}{}{凡拉尼}                         # RCVelani.int    ; Velani, the payoff man for Savinelli
{913}{}{芬爾堂}                         # RCFern.int      ; Ferndown, the payoff man for Wade
{914}{}{龍}                             # FCDragon.int    ; The Dragon, San Fran
{915}{}{馬廄工人}                       # mcSblBoy.int    ; Modoc Stable Boy
{916}{}{商人}                           # mcTrader.int    ; Modoc Trader
{917}{}{鎮民}                           # mcPerson.int    ; Modoc Townspeople
{918}{}{史拉格}                         # mcSlgExt.int    ; Ghost Farm Slag Exit Guard
{919}{}{史拉格}                         # mcSlgGrd.int    ; Ghost Farm Slag Enterance Guard
{920}{}{羅潘}                           # FCLoPan.int     ; Lo Pan in San Fran.
{921}{}{派特爵}                         # FCBadger.int    ; Badger in San Fran.
{922}{}{賈序}                           # RCJosh.int      ; Josh Laurance of Redding
{923}{}{卡麥那多}                       # RCCamint.int    ; Caminetto in bar fight in redding
{924}{}{貝蒂}                           # RCBette.int     ; Blasphemous Bette in bar fight in redding
{925}{}{槍商}                           # FCGunmer.int    ; San Fran's gun Merchant
{926}{}{門}                             # ZIWodDor.int    ; Generic Wooden Door
{927}{}{門}                             # ZIMtlDor.int    ; Generic Metal Door
{928}{}{發射器}                         # SSEmtN2.int     ; Emitter in NCR area 2
{929}{}{鼠神}                           # ZCRatGod.int    ; Rat God in Klamath
{930}{}{}                               # ECBox.int       ; Random box that has stuff in it.
{931}{}{卡賈}                           # ECKaga1.int     ; Random Encounter Kaga 1
{932}{}{卡賈}                           # ECKaga2.int     ; Random Encounter Kaga 2
{933}{}{卡賈}                           # ECKaga3.int     ; Random Encounter Kaga 3
{934}{}{卡賈}                           # ECKaga4.int     ; Random Encounter Kaga 4
{935}{}{卡賈}                           # ECKaga5.int     ; Random Encounter Kaga 5
{936}{}{獎金獵人}                       # ECBHunter.int   ; Random Encounter Bounty Hunter
{937}{}{電腦}                           # VIMedCom.int    ; Vault City Medical Computer
{938}{}{電腦}                           # VICenCom.int    ; Vault City Central Computer
{939}{}{電腦}                           # VIAloCom.int    ; Vault City Allocation Computer
{940}{}{達洛}                           # VCDarrow.int    ; Vault City Sub-Amenities Officer Darrow
{941}{}{費爾}                           # VCFarrel.int    ; Vault City Sub-Amenities Officer Farrell
{942}{}{酒吧客人}                       # VCBarPat.int    ; Vault City Bar Patron
{943}{}{地下掩體市公民}                 # VCWrkCit.int    ; Vault City Working Citizen
{944}{}{地下掩體市奴僕}                 # VCSlave.int     ; Vault City Slave
{945}{}{通風口}                         # VIShft2b.int    ; Vault City Ventilation Shaft 2B
{946}{}{查理}                           # VCCharli.int    ; Vault City Puking Charlie
{947}{}{冷卻器控制介面}                 # GSValve.int     ; Gecko Coolant Control Panel
{948}{}{牛糞}                           # ziBraPoo.int    ; Generic BRAHMIN SHIT!!! YES YES YES
{949}{}{葛蘭}                           # scWesGrd.int    ; Westin's Force Field Guard
{950}{}{發射器}                         # SSEmiWes.int    ; Westin's Force Field Emitter
{951}{}{發射器}                         # SSEmiWe1.int    ; Westin's force field on the other map.
{952}{}{電腦控制臺}                     # SICmpWes.int    ; Westin's computer terminal for the field.
{953}{}{皇帝電腦終端機v8.8}             # FSEmpTer.int    ; Computer Terminal in San Fran
{954}{}{副總統飛鳥}                     # QCBird.int      ; Enclave, Vice President Bird
{955}{}{馬丁}                           # QCMartin.int    ; Enclave, Martin Frobishner, V13 spokesman
{956}{}{李健}                           # FCKenLee.int    ; Ken Lee in San Francisco
{957}{}{葛蘭耐特上校}                   # QCGranit.int    ; Sgt. Granite of the Enclave Patrol
{958}{}{法蘭克．荷瑞根}                 # QCFrank.int     ; Secret Service Agent Frank (End Boss)
{959}{}{地圖}                           # GeckJunk.int    ; Map Script for Gecko Junkyard
{960}{}{地圖}                           # GeckTunl.int    ; Map Script for Gecko Tunnels
{961}{}{門}                             # SSFrgDor.int    ; Fergus's Door script
{962}{}{門}                             # SSGunDor.int    ; Gunther's Door script to Tandi
{963}{}{門}                             # SSFlxDor.int    ; Felix's Door script
{964}{}{繩子}                           # SSRope.int      ; Rope.. for you to climb
{965}{}{發射器}                         # SSEmiEnt.int    ; Emitter in Ncr Entrance
{966}{}{卡林博士}                       # QCCurlng.int    ; Dr. Charles Curling, Chem Corps.
{967}{}{佈告欄}                         # SSSign.int      ; Sign in NCR Entrance
{968}{}{地鼠}                           # mcMolRat.int    ; Ghost Farm Mole Rat
{969}{}{總統的秘書}                     # QCPrsSec.int    ; President's personal intern (uh sectertary)
{970}{}{湯姆．莫雷}                     # QCMurray.int    ; Tom Murray, head of AEC
{971}{}{堅固的門}                       # SSCrpDor.int    ; Craps table door in NCR
{972}{}{鎮民}                           # mcPeasan.int    ; Modoc Peasant, they attack the farm
{973}{}{地下掩體市行政區}               # VCtyCocl.int    ; Map Script Vault City Council Area
{974}{}{空氣清淨機}                     # HSPurify.int    ; Air Purifier for Broken Hills
{975}{}{石頭}                           # esEntRks.int    ; Military Base Enterance Rocks
{976}{}{賭徒}                           # RCGamble.int    ; Redding Generic Gamblers
{977}{}{假的屍體}                       # HtCorpse.int    ; Spatial Script for Corpses
{978}{}{來自ＮＣＲ的騙子}               # SCCheat.int     ; Cheat Character for NCR
{979}{}{犯人}                           # QCGenPrs.int    ; Enclave Generic Prisoner
{980}{}{市民}                           # QCGenCit.int    ; Enclave Generic Citizens
{981}{}{衛兵}                           # QCGenGrd.int    ; Enclave Generic Guards
{982}{}{科學家}                         # QCGenSci.int    ; Enclave Generic Scientist
{983}{}{終端機}                         # QIPzlTrm.int    ; Enclave terminal in the Puzzle Level
{984}{}{}                               # etEnter.int     ; Military Base Enterance Spacial Message
{985}{}{}                               # etBattle.int    ; Military Base Battle Area Spacial Message
{986}{}{發射器}                         # SSEmiEn1.int    ; Ncr emitters for ncr entrance on map 1
{987}{}{門}                             # QIBstDr1.int    ; Blast Door for Reactor Off to remain closed
{988}{}{門}                             # QIBstDr2.int    ; Blast Door for Reactor On to remain closed
{989}{}{達洛的存貨}                     # VIDarBox.int    ; Vault City Darrow Shop Inventory
{990}{}{門}                             # HSCrlDr.int     ; Jail cell door for Broken Hills
{991}{}{超級變種人}                     # ecTlkMut.int    ; Military Base Conversation Mutants
{992}{}{化學家}                         # fcChemst.int    ; Chemist in San Francisco
{993}{}{古朗多}                         # ecGrunde.int    ; Military Base Mouse Hunter
{994}{}{小孩}                           # ecMelKid.int    ; Some Town USA, Melchior's Kid
{995}{}{視網膜掃瞄器}                   # WIRetScn.int    ; Retinal Scanner in the Sieera Base
{996}{}{電梯門}                         # WIElvDor.int    ; Elevator Door in the Seirra Base
{997}{}{生化箱}                         # WIBrkBrn.int    ; Broken Brain Bot in the Sierra Base
{998}{}{牆}                             # WIScrtDr.int    ; Sierra Base Secert Door
{999}{}{地圖}                           # broken2.int     ; Map Script for Broken Hills Map 2
{1000}{}{費羅的存貨}                    # VIFarBox.int    ; Vault City Farrell Shop Inventory
{1001}{}{哈利的存貨}                    # VIHarBox.int    ; Vault City Harry Shop Inventory
{1002}{}{盒子}                          # VICtyBox.int    ; Vault City Courtyard Temp Inventory Box
{1003}{}{盒子}                          # VIDwtBox.int    ; Vault City Downtown Temp Inventory Box
{1004}{}{德瑞克}                        # dcDerek.int     ; Derek in the Den
{1005}{}{塔比的朋友}                    # dcTubFri.int    ; Tubby's Junkie Friends in the Den
{1006}{}{賭徒}                          # dcGamble.int    ; Gamblers in the Den
{1007}{}{奴隸}                          # dcSlave.int     ; Pen Slaves in the Den
{1008}{}{衛兵}                          # dcMetRom.int    ; Metzger Room Guard in the Den
{1009}{}{奴隸販子}                      # dcPenGrd.int    ; Slaver Pen Guard in the Den
{1010}{}{蘿拉}                          # dcLara.int      ; Lara in the Den
{1011}{}{泰勒}                          # dcTyler.int     ; Tyler in the Den
{1012}{}{馬克}                          # dcMarc.int      ; Marc in the Den
{1013}{}{佈告欄}                        # diBulBrd.int    ; Bulletin Board in the Den
{1014}{}{奴隸販子}                      # dcVicGrd.int    ; Vic Guard in the Den
{1015}{}{奴隸販子}                      # dcSlvGrt.int    ; Slaver Greeter in the Den
{1016}{}{弗瑞德}                        # dcFred.int      ; Fred in the Den
{1017}{}{盒子}                          # diFliBox.int    ; Flick Box in the Den
{1018}{}{盒子}                          # diMomBox.int    ; Mom Box in the Den
{1019}{}{盒子}                          # diSmiBox.int    ; Smitty Box in the Den
{1020}{}{後車箱}                        # ZICrTrnk.int    ; generic script for Car Trunk
{1021}{}{安全門}                        # QIPzlDor.int    ; Door for the puzzle room in the Enclave
{1022}{}{電腦終端機}                    # FSPhySta.int    ; Physics computer station in San Fran
{1023}{}{電腦終端機}                    # FSBioSta.int    ; Biology computer station in San Fran
{1024}{}{電腦終端機}                    # FSCheSta.int    ; Chemistry computer station in San Fran
{1025}{}{朱流}                          # FCLaoCho.int    ; Merchant in San Fran
{1026}{}{}                              # FIPaper.int     ; Scrap Papers that combine should only be put on one of the peaces.
{1027}{}{}                              # CSVent.int      ; Ventilation shaft for Navarro
{1028}{}{地圖}                          # EncTrp.int      ; Map Script for Enclave Trap Rooms
{1029}{}{屍體}                          # HtBody.int      ; Script for dead bodies in Broken Hills
{1030}{}{電線}                          # QIWires.int     ; Wires on the ground in the trap room
{1031}{}{盒子}                          # diMetBox.int    ; Metzger Box from Slave Crap
{1032}{}{奴隸販子}                      # dcRunSlv.int    ; Den Slave Run Fleeing Slaves
{1033}{}{奴隸販子}                      # dcAtkSlv.int    ; Den Slave Run Hostile Slaves
{1034}{}{奴隸販子}                      # dcRnSlvr.int    ; Den Slave Run Slavers
{1035}{}{錢幣}                          # FCChip.int      ; Chip in San Fran no splean
{1036}{}{反應爐}                        # QIReactr.int    ; Reactor in the Enclave
{1037}{}{反應爐電腦}                    # QIRctrCm.int    ; Reactor Computer in the Enclave
{1038}{}{收銀員}                        # RCCshTnd.int    ; Redding Cash Tender in the Casino
{1039}{}{錢箱}                          # RICshBox        ; Cash Box for the Cash Tender
{1040}{}{瓦那明球}                      # RCWanami.int    ; Wanamingo
{1041}{}{酒吧客人}                      # dcStory1.int    ; Story Teller 1 in the Den
{1042}{}{酒吧客人}                      # dcStory2.int    ; Story Teller 2 in the Den
{1043}{}{牢門}                          # RIJalDor.int    ; Jail Door in Redding
{1044}{}{蘇}                            # FCSuze.int      ; Suze in San Fran
{1045}{}{朗麥爾隊長}                    # FCRonMey.int    ; Captain Ron Meyers
{1046}{}{門}                            # diPenDor.int    ; Slave Pen Door in the Den
{1047}{}{瓦那明球礦坑}                  # RedWan1.int     ; Map Script for Wanamingo Mine
{1048}{}{瓦那明球礦坑入口}              # RedWane.int     ; Map Script for Wanamingo Mine Entrance
{1049}{}{「青蛙」．摩頓}                # RCFrog.int      ; Frog Morton
{1050}{}{達夫}                          # FCDaveh.int     ; Dave Handy in San Fran
{1051}{}{門}                            # diVicDor.int    ; Vic's Room Door in the Den
{1052}{}{門}                            # diRomDor.int    ; Metzger's Room Door in the Den
{1053}{}{查理}                          # vccharly.int    ; Puking Charlie in Vault Courtyard
{1054}{}{畫}                            # SIPaint.int     ; Revales Vault 13 on examination.
{1055}{}{地圖}                          # SFChina.int     ; San Fran China Map
{1056}{}{酒保}                          # VCCouBar.int    ; Vault City Council Area Bartender
{1057}{}{盒子}                          # VIBarBox.int    ; Vault City Slave Sale Inventory Dump
{1058}{}{自動醫生}                      # VIAutDoc.int    ; Vault City Courtyard Auto-Doc
{1059}{}{}                              # RIMinEnt.int    ; Entrance Back to the Mines
{1060}{}{坑道}                          # RedMTun.int     ; Map Script for Mining Tunnel
{1061}{}{機器人}                        # KCRob.int       ; Robot on Klamath Canyon
{1062}{}{}                              # FiGunTbl.int    ; Gun Merchant table in San fran
{1063}{}{地圖}                          # KlaMall.int     ; Map Script for Klamath Mall area
{1064}{}{地圖}                          # KlaTrap.int     ; Map Script for Klamath Still area
{1065}{}{莉蒂雅}                        # VCDwnBar.int    ; Vault City Downtown Bartender
{1066}{}{}                              # RedDTun.int     ; Redding Downtown Tunnels
{1067}{}{火箭人}                        # FCRocMan.int    ; Rocket man in San Fran
{1068}{}{AHS-7}                         # FCOz7.int       ; Oz 7 in San Fran
{1069}{}{克拉克特}                      # FCCrocke.int    ; Crockett in San Fran
{1070}{}{阿曼達}                        # VCAmanda.int    ; Vault City Coutryard Amanda, Joshua's Wife
{1071}{}{約瑟}                          # VCJoshua.int    ; Vault City Courtyard Joshua, Slave
{1072}{}{薇拉瑞}                        # VCMainWk.int    ; Valerie, Vic's Daughter and Maintence Worker
{1073}{}{教學系統}                      # VITeach.int     ; Vault City Teaching System
{1074}{}{箱子}                          # diCrate.int     ; Den Crate in Church
{1075}{}{隨地小便的人}                  # VCUrine.int     ; Peeing Guy in Vault City Council Area
{1076}{}{科提斯}                        # VCCurtis.int    ; Curtis, Amanda and Joshua's Son
{1077}{}{馬克}                          # FCMarc.int      ; Marc, Punk in San Fran
{1078}{}{電腦}                          # FSElComp.int    ; Hubologists computer
{1079}{}{AHS-9}                         # FCOz9.int       ; Hubologist main dude
{1080}{}{衛兵}                          # FCElGrd.int     ; Hubologist's guards
{1081}{}{一堆石頭}                      # VIRocks.int     ; Pile of Rocks w/ Hidden Wrench
{1082}{}{門}                            # VIVltDor.int    ; Vault City 2nd floor doors
{1083}{}{衛兵}                          # dcRebGrd.int    ; Den Rebecca Guard
{1084}{}{衛兵}                          # dcRebDor.int    ; Den Rebecca Door Guard
{1085}{}{門}                            # diRebDor.int    ; Den Rebecca Door
{1086}{}{通緝標示}                      # ZSWsign.int     ; Generic Wanted Sign
{1087}{}{王博士}                        # FCDrWong.int    ; Dr. Wong in San Fran area
{1088}{}{桌子}                          # FIlaotbl.int    ; Lao Cho's stock tables in san Fran
{1089}{}{門}                            # WILv1Dor.int    ; Locked Door on Level 1 Entrance               # local_vars=8
{1090}{}{混混}                          # FCFemPnk.int    ; San Fran Female punk
{1091}{}{混混}                          # FCMalPnk.int    ; San Fran Male Punk
{1092}{}{萊恩}                          # FCRyan.int      ; San Fran Punk Ryan
{1093}{}{盒子}                          # HIBh1Box.int    ; Broken Hills Temp Inventory Box
{1094}{}{}                              # FCJuavki.int    ; Juan and Vikkin in San Fran Elron Camp
{1095}{}{地下水道通道}                  # HIManHol.int    ; Manhole to Basement in Liz's Store
{1096}{}{地圖}                          # SFElronb.int    ; Elron Base map Script
{1097}{}{梯子}                          # HILadder.int    ; Ladder up to Liz's Store
{1098}{}{沙包}                          # WIPnchBg.int    ; Punching Bag in the Sierra Depot
{1099}{}{門}                            # WIBayDor.int    ; Sierra Base Repair Bay Door
{1100}{}{警鈴}                          # GSAlarm.int     ; Gecko Reactor alarm
{1101}{}{地板}                          # WIPlTrp2.int    ; Plasma Floor Trap Level 2 of Seirra
{1102}{}{地板}                          # WIPlTrp3.int    ; Plasma Floor Trap Level 2 of Seirra
{1103}{}{地板}                          # WIPlTrp4.int    ; Plasma Floor Trap Level 2 of Seirra
{1104}{}{地板}                          # WIPlTrp5.int    ; Plasma Floor Trap Level 2 of Seirra
{1105}{}{地板}                          # WIPlTrp6.int    ; Plasma Floor Trap Level 2 of Seirra
{1106}{}{地板}                          # WIPlTrp7.int    ; Plasma Floor Trap Level 2 of Seirra
{1107}{}{地板}                          # WIPlTrp8.int    ; Plasma Floor Trap Level 2 of Seirra
{1108}{}{地板}                          # WIPlTrp9.int    ; Plasma Floor Trap Level 2 of Seirra
{1109}{}{地板}                          # WIPlTrpA.int    ; Plasma Floor Trap Level 2 of Seirra
{1110}{}{地板}                          # WIPlTrpB.int    ; Plasma Floor Trap Level 2 of Seirra
{1111}{}{地板}                          # WIPlTrpC.int    ; Plasma Floor Trap Level 2 of Seirra
{1112}{}{地板}                          # WIPlTrpD.int    ; Plasma Floor Trap Level 2 of Seirra
{1113}{}{地板}                          # WIPlTrpE.int    ; Plasma Floor Trap Level 2 of Seirra
{1114}{}{地板}                          # WIPlTrpF.int    ; Plasma Floor Trap Level 2 of Seirra
{1115}{}{發射器}                        # WSEmit4a.int    ; Emitter, Level 4 in Sierra Base
{1116}{}{發射器}                        # WSEmit4b.int    ; Emitter, Level 4 in Sierra Base
{1117}{}{發射器}                        # WSEmit4c.int    ; Emitter, Level 4 in Sierra Base
{1118}{}{力場}                          # WSFeld4a.int    ; Force Field, Level 4 in Sierra Base
{1119}{}{力場}                          # WSFeld4b.int    ; Force Field, Level 4 in Sierra Base
{1120}{}{力場}                          # WSFeld4c.int    ; Force Field, Level 4 in Sierra Base
{1121}{}{哈伯教}                        # FCElrInd.int    ; Elron Indoctrinee
{1122}{}{電腦}                          # FStnkCmp.int    ; Posiden Tanker Computer
{1123}{}{門}                            # WIBnkDor.int    ; Bunker Door for the Sierra Depot
{1124}{}{門}                            # miGate.int      ; Modoc Gate
{1125}{}{盒子}                          # WITrpBx1.int    ; Sierra Base Trapped Box
{1126}{}{摩頓兄弟}                      # RCMorBrs.int    ; Morton Brothers, Inc.
{1127}{}{發射器}                        # FSEmt1.int      ; Force Field emitter 1 in San Fran
{1128}{}{發射器}                        # FSEmt2.int      ; Force Field emitter 2 in San Fran
{1129}{}{發射器}                        # FSEmt3.int      ; Force Field emitter 3 in San Fran
{1130}{}{地圖}                          # Cave6.int       ; Fake Vault 13 Cave map
{1131}{}{俠特}                          # VCChet.int      ; Illicit Allocations Officer Chet
{1132}{}{地圖}                          # NewRVB.int      ; New Reno Helicopter Script Map
{1133}{}{飛鳥}                          # nsVertib.int    ; New Reno Helicopter Script Vertibird
{1134}{}{沙爾瓦多的衛兵}                # ncHSSal1.int    ; New Reno Helicopter Script Salvatore 1
{1135}{}{沙爾瓦多的衛兵}                # ncHSSal2.int    ; New Reno Helicopter Script Salvatroe 2
{1136}{}{士兵}                          # ncHSPow1.int    ; New Reno Helicopter Script Power Armor 1
{1137}{}{士兵}                          # ncHSPow2.int    ; New Reno Helicopter Script Power Armor 2
{1138}{}{箱子}                          # niHSCrat.int    ; New Reno Helicopter Script Crate
{1139}{}{韓地先生}                      # ncHSHand.int    ; New Reno Helicopter Script Handy
{1140}{}{沙爾瓦多的衛兵}                # ncHSGSal.int    ; New Reno Helicopter Script Salvatore Guard
{1141}{}{特別任務}                      # ntHSGrd.int     ; New Reno Helicopter Script Guarding Spacial
{1142}{}{門}                            # niEldDor.int    ; New Reno Elderidge Door
{1143}{}{門}                            # niSalDor.int    ; New Reno Salvatore Door
{1144}{}{門}                            # niMyrDor.int    ; New Reno Myron Door
{1145}{}{}                              # FcMonst.int     ; Monster in the PMS Tanker
{1146}{}{地圖}                          # SFTanker.int    ; San Fran Tanker map
{1147}{}{奴隸}                          # VCSlav2.int     ; Vault City Prisoner Slaves
{1148}{}{地下掩體市公民}                # VCBarCit.int    ; Vault City Bar Patron
{1149}{}{門}                            # niBasDor.int    ; New Reno Locking Doors
{1150}{}{拳擊手}                        # ncFightr.int    ; New Reno Boxer Actually Fighting
{1151}{}{門}                            # RIVltDor.int    ; Locked Vault Door in Redding
{1152}{}{查恩}                          # CcXarn.int      ; Xarn in Navarro
{1153}{}{羅烏}                          # CcRaul.int      ; Raul in Navarro
{1154}{}{昆西}                          # CcQuincy.int    ; Quincy in Navarro
{1155}{}{總管}                          # CcQmstr.int     ; Quartermaster in Navarro
{1156}{}{衛兵}                          # CcMedGrd.int    ; Med Lab Guard in Navarro
{1157}{}{機器狗}                        # CcK9.int        ; K9 in Navarro
{1158}{}{博士}                          # CcDoctor.int    ; Dr Shreber in Navarro
{1159}{}{技術員}                        # CcATech.int     ; Air Tech in Navarro
{1160}{}{技術員}                        # CcACon.int      ; Air Control in Navarro
{1161}{}{衛兵}                          # CcDrGrd.int     ; Door Guard in Navarro
{1162}{}{衛兵}                          # Ccggbak.int     ; Gate Guard Backup in Navarro
{1163}{}{衛兵}                          # CcGrdca.int     ; Guard (combat armor) in Navarro
{1164}{}{衛兵}                          # CcGrdpa.int     ; Guard (power armor) in Navarro
{1165}{}{技術員}                        # CcTech1.int     ; Com Tech1 in Navarro
{1166}{}{技術員}                        # CcTech2.int     ; Com Tech2 in Navarro
{1167}{}{技術員}                        # CcComp1.int     ; Computer Tech1 in Navarro
{1168}{}{技術員}                        # CcComp2.int     ; Computer Tech2 in Navarro
{1169}{}{坍坊}                          # HICaveIn.int    ; Broken Hills Caved-In mine
{1170}{}{英克雷軍巡邏兵}                # QCEPSqad.int    ; Enclave EP Squad (joins player in fighting
{1171}{}{門}                            # QIEndDor.int    ; Doors at the End Fight Area
{1172}{}{地圖}                          # EncDet.int      ; Map Script for Enclave Detention Center
{1173}{}{地圖}                          # EncDock.int     ; Map Script for Enclave Dock
{1174}{}{地圖}                          # EncGd.int       ; Map Script for Enclave Guard Barracks
{1175}{}{地圖}                          # EncPres.int     ; Map Script for Enclave Presidential Area
{1176}{}{地圖}                          # EncRetr.int     ; Map Script for Enclave Reactor Area
{1177}{}{地圖}                          # EncFite.int     ; Map Script for Enclave Fight Area
{1178}{}{安全機器人}                    # QCSecBot.int    ; Enclave Security Robot
{1179}{}{盒子}                          # niTulBox.int    ; New Reno Poor Box
{1180}{}{遺體}                          # hiDead.int      ; Dead body in Broken Hills Tunnels
{1181}{}{盒子}                          # HiJacBox.int    ; Broken Hills Jacob inventory box
{1182}{}{盒子}                          # HiDocBox.int    ; Broken Hills Doc Holliday Inventory box
{1183}{}{盒子}                          # HiOutBox.int    ; Broken Hills Outfitter inventory box
{1184}{}{商隊衛兵}                      # RCCvnGrd.int    ; Generic Caravan Guard
{1185}{}{商隊駕駛}                      # RCCvnDrv.int    ; Generic Caravan Driver
{1186}{}{拳擊撥報員}                    # ncAnounc.int    ; New Reno Boxing Anouncer
{1187}{}{拳擊女郎}                      # ncRngGrl.int    ; New Reno Ring Grrrl
{1188}{}{拳擊手}                        # ncPrzFtr.int    ; New Reno Prize Fighter
{1189}{}{門}                            # VIVltDr2.int    ; Vault Doors in Vault 8
{1190}{}{騙子}                          # ncCheat.int     ; New Reno Cheat Character
{1191}{}{實體顯像磁片}                  # WIGNNDsk.int    ; Sierra Base GNN Transscript
{1192}{}{實體顯像磁片}                  # WIMisDsk.int    ; Sierra Base Mission Statement Disk
{1193}{}{實體顯像磁片}                  # FIElrDsk.int    ; Hubologist Holodisk
{1194}{}{紙條}                          # HINote.int      ; Script for Francis/Zaius Note
{1195}{}{狗肉}                          # ECDogMet.int    ; Dog Meat from Special random encounter
{1196}{}{貓爪雜誌#5}                    # niCatPw5.int    ; New Reno Cat's Paw magazine 5
{1197}{}{歹徒地圖}                      # niRaiMap.int    ; New Reno Raiders Map in Bishop's Safe
{1198}{}{狗}                            # ECPariah.int    ; Pariah Dog in Low Luck encounter
{1199}{}{警笛}                          # QIKlaxon.int    ; Klaxon Lights for Enclave when under alert
{1200}{}{礦坑}                          # IIMine.int      ; Mines in Raiders Cave
{1201}{}{洞穴}                          # IIPit.int       ; Pits in the Raiders Cave
{1202}{}{油艦商人}                      # FCTnkGmr.int    ; Tanker Gun Merchant San Fran
{1203}{}{油艦酒保}                      # FCTnkBar.int    ; Tanker Bar Tender
{1204}{}{油艦商人}                      # FCTnkMer.int    ; Tanker Merchant
{1205}{}{}                              # FITGunTb.int    ; Tanker Gun Mer's table
{1206}{}{}                              # FITMerTb.int    ; Tanker Merchant's Table
{1207}{}{發射器}                        # FSPemtr1.int    ; Palace Emitter 1
{1208}{}{發射器}                        # FSPemtr2.int    ; Palace Emitter 2
{1209}{}{發射器}                        # FSPemtr3.int    ; Palace Emitter 3
{1210}{}{發射器}                        # FSEmpEmt.int    ; Emporor Computer's Force Field
{1211}{}{異塵餘生２攻略本}              # niF2Hint.int    ; New Reno Fallout 2 Hintbook
{1212}{}{}                              # csTouch.int     ; Script to signal if dude touches container objects (in Navarro)
{1213}{}{}                              # csArea.int      ; Script to signal if dude enters an area (in Navarro)
{1214}{}{衛兵}                          # RCAscGrd.int    ; Generic Guard for Ascorti's Bar
{1215}{}{採礦者}                        # ECLdPros.int    ; Random Encounter Lead Prospector
{1216}{}{私販酒者}                      # ECLdBoot.int    ; Random Encounter Lead Bootlegger
{1217}{}{}                              # csOpen.int      ; Script to signal if dude uses door w/o permision (in Navarro)
{1218}{}{丹}                            # hcDan.int       ; Dan, Spouse of murdered conspirator.
{1219}{}{爛喜劇演員}                    # ncComedi.int    ; New Reno Comedian
{1220}{}{歌手}                          # ncBand.int      ; New Reno Trashcan Band
{1221}{}{地圖}                          # ARDead.int      ; Destroyed Arroyo Bridge map script
{1222}{}{}                              # csGate.int      ; Script to signal if dude uses gate w/o permision (in Navarro)
{1223}{}{墳墓}                          # niWilGrv.int    ; New Reno Coffin Willie's Grave
{1224}{}{威利}                          # ncWillie.int    ; New Reno Coffin Willie
{1225}{}{沒有鍵盤的入口控制電腦}        # FSFobTer.int    ; Fob Terminal
{1226}{}{沒有鍵盤的入口}                # FSFobDor.int    ; Fob Door
{1227}{}{電腦}                          # ccNComp.int     ; Navarro Computer
{1228}{}{卡歐}                          # vcKohl.int      ; Vault City Info Officer Kohl
{1229}{}{小孩}                          # ECChild.int     ; Random Encounter Children
{1230}{}{廚師}                          # ccCook.int      ; Navarro Cook
{1231}{}{砲臺}                          # ccTurret.int    ; Navarro Turret
{1232}{}{布萊恩}                        # hcBrian.int     ; Brian, the Power Technician
{1233}{}{發電機}                        # hiPower.int     ; Power Generator for Broken Hills
{1234}{}{控制臺}                        # hiConsole.int   ; Power Station Console in Broken Hills
{1235}{}{大螞蟻}                        # hcAnt1.int      ; Standard Broken Hills Ant
{1236}{}{大螞蟻}                        # hcAnt2.int      ; Broken Hills Ant - Missing Person Quest
{1237}{}{門}                            # csXDoor.int     ; Another lousy door script -signals xarn to leave
{1238}{}{}                              # htSecret.int    ; Spatial for secret area of Broken Hills Mine
{1239}{}{盒子}                          # niEthBox.int    ; New Reno Ethyl Wright Shop Box
{1240}{}{艾力克}                        # hcEric.int      ; Eric the Smelly Boy, Broken Hills
{1241}{}{}                              # htFlies.int     ; Spatial Flies script for Broken Hills
{1242}{}{盒子}                          # viRanBox.int    ; Randal's Stock Box in Vault City
{1243}{}{大毒蠍}                        # iiScorp.int     ; Raiders Scorpions 2X poison
{1244}{}{珍}                            # RCJane.int      ; Redding Jackpot Jane
{1245}{}{}                              # VTAloMrk.int    ; Spatial Script for Allocation Computer VCity
{1246}{}{地圖}                          # Cave7.int       ; Fake Vault 13 map
{1247}{}{嗶嗶小子}                    # niDermal.int    ; New Reno Dermal Pip Boy
{1248}{}{波奇}                          # ncEldDog.int    ; New Reno Eldridge Dogs
{1249}{}{羅特雷}                        # RCRatray.int    ; Rattray, Doc Johnson's assistant
{1250}{}{夫婦}                          # HCHusWif.int    ; Mutant Husband/Wife Broken Hills
{1251}{}{羅潘衛兵}                      # FCLoGrd.int     ; LoPan Guard in San Fran
{1252}{}{地圖}                          # Navarro.int     ; Map script for Navarro
{1253}{}{門}                            # VIVltDr3.int    ; Vault Door in Vault 8 - Martin
{1254}{}{機器狗}                        # CcFak9.int      ; Fake K-9 Scenery obj
{1255}{}{路克}                          # FCNLuke.int     ; Luke in NCR
{1256}{}{約瑟}                          # FCDJosh.int     ; Joshua BOS in the Den
{1257}{}{門}                            # iiLockDr.int    ; Gates in Raiders area
{1258}{}{麥特}                          # FCFmatt.int     ; Matt in San Fran BOS
{1259}{}{門}                            # FSBroDor.int    ; Brotherhood Door
{1260}{}{衛兵}                          # hcGrd2.int      ; Bank Guard 2 in Broken Hills
{1261}{}{門}                            # QIGeckDr.int    ; Door Requiring the player to use the geck
{1262}{}{電腦}                          # FSFace.int      ; Ace Computer system in San Fran
{1263}{}{終端機}                        # QITurTrm.int    ; Generic Enclave Turret Terminal
{1264}{}{砲臺}                          # QCTurret.int    ; Enclave Turrets
{1265}{}{恰克．史度傑}                  # hcChuck.int     ; Chuck Stodgers, Broken Hills
{1266}{}{}                              # htChuck.int     ; Spatial Script for waking up Chuck
{1267}{}{終端機}                        # viTerm.int      ; Vault City Vault Terminal
{1268}{}{幫派份子}                      # RCMotGng.int    ; Frog Morton's gang
{1269}{}{作弊者}                        # ccCheat.int     ; Cheat Character in Navarro
{1270}{}{}                              # FSTnkrdr.int    ; Tanker Doors in San Fran
{1271}{}{平民}                          # OCPeaon.int     ; NCR peaons
{1272}{}{羅凡德之花}                    # diRebBok.int    ; Den Becky's Book
{1273}{}{毒蠍子}                        # hcScorp.int     ; Broken Hills Scorpion
{1274}{}{教授}                          # hcProf.int      ; Broken Hills Professor
{1275}{}{盒子}                          # hiPrfBx1.int    ; Professor's Box in Broken Hills
{1276}{}{盒子}                          # hiPrfBx2.int    ; Professor's Box in Broken Hills
{1277}{}{西莫}                          # hcSeymore.int   ; Seymour the talking Plant/Broken Hills
{1278}{}{約翰．蘇羅文}                  # hcSulvan.int    ; John Sullivan - Broken Hills
{1279}{}{藍爾皮}                        # hcLumpy.int     ; Lumpy the car accident victim - Broken Hills
{1280}{}{}                              # BISpyHol.int    ; Spy Holodisk for NCR
{1281}{}{}                              # SIHisHol.int    ; NCR History Holodisk
{1282}{}{}                              # SIWesHol.int    ; Westin Holodisk
{1283}{}{衛兵}                          # SCBGrd.int      ; Buster's Guard
{1284}{}{}                              # SIElnObj.int    ; Elise Notify Object
{1285}{}{}                              # SIGcaObj.int    ; NCR Guard Captain notify obj
{1286}{}{泰豐}                          # hcTyphon.int    ; Typhon, Son of Set - Broken Hills
{1287}{}{保鏢}                          # ECBdyGrd.int    ; BodyGuard in Vignette
{1288}{}{地圖}                          # GamMovie.int    ; Game Movie map
{1289}{}{鎖櫃}                          # ziLocker.int    ; Generic Locker Script
{1290}{}{水井}                          # hiWell.int      ; Broken Hills Well
{1291}{}{米奇}                          # hcMicky.int     ; Mickey the Dwarf - Broken Hills
{1292}{}{砲臺}                          # WCTurret.int    ; Turret for Sierra Depot
{1293}{}{老僵屍}                        # hcOldGhl.int    ; Ghouls in Old-Folks Home - Broken Hills
{1294}{}{追蹤者}                        # hcHench.int     ; Broken Hills Outfitter Henchmen
{1295}{}{艾爾摩}                        # hcElmo.int      ; Elmo - Broken Hills
{1296}{}{馬桶}                          # niToilet.int    ; Toilet - Contains Grenades - New Reno
{1297}{}{十字架}                        # niCross.int     ; Cross - Golgotha - Buried Cash
{1298}{}{犁}                            # viPlow1.int     ; Plow - Vault City
{1299}{}{犁}                            # viPlow2.int     ; Plow - Vault City
{1300}{}{毒蠍子}                        # kcScorpa.int    ; Attacking scorpion in klamath
{1301}{}{發電機}                        # kcGnratr.int    ; Generator player repairs in toxic caves
{1302}{}{門}                            # kcLvatr.int     ; Elevator door in toxic caves
{1303}{}{門}                            # SIVDor.int      ; Vortis Slave Door
{1304}{}{醫療嗶嗶小子}                  # niMedica.int    ; New Reno "Doctor Skill" Upgrade
{1305}{}{鎖櫃}                          # niPrstLk.int    ; New Reno Prostitute"Locker"
{1306}{}{鎖櫃}                          # niBigJLk.int    ; New Reno Big Jesus "Locker"
{1307}{}{鎖櫃}                          # niMor1Lk.int    ; New Reno Mordino No Lock/No Ignore "Locker"
{1308}{}{鎖櫃}                          # niBoxrLk.int    ; New Reno Boxer "Locker"
{1309}{}{鎖櫃}                          # niBis1Lk.int    ; New Reno Bishop Family OK "Locker"
{1310}{}{鎖櫃}                          # niPornLk.int    ; New Reno Porn Actress "Locker"
{1311}{}{鎖櫃}                          # niBtchLk.int    ; New Reno Bitch "Locker"
{1312}{}{鎖櫃}                          # niBis2Lk.int    ; New Reno Bishop Family NO IGNORE "Locker"
{1313}{}{鎖櫃}                          # niEldrLk.int    ; New Reno Eldridge "Locker"
{1314}{}{鎖櫃}                          # niWrT1Lk.int    ; New Reno Wright Teen NO IGNORE "Locker"
{1315}{}{鎖櫃}                          # niOWriLk.int    ; New Reno Orville Wright "Locker"
{1316}{}{鎖櫃}                          # niWrT2Lk.int    ; New Reno Wright Teen FAMILY IGNORE "Locker"
{1317}{}{鎖櫃}                          # niMor1Lk.int    ; New Reno Mordino FAMILY IGNORE "Locker"
{1318}{}{鎖櫃}                          # niMyGdLk.int    ; New Reno Myron Guard "Locker"
{1319}{}{鎖櫃}                          # niMor2Lk.int    ; New Reno Mordino NO IGNORE "Locker"
{1320}{}{鎖櫃}                          # niMyrnLk.int    ; New Reno Myron "Locker"
{1321}{}{鎖櫃}                          # niChp1Lk.int    ; New Reno Chop Shop Boy LOCKED "Locker"
{1322}{}{鎖櫃}                          # niChp2Lk.int    ; New Reno Chop Shop Boy NO-LOCK "Locker"
{1323}{}{鎖櫃}                          # niTryLk.int     ; New Reno Tray "Locker"
{1324}{}{鎖櫃}                          # niMor3Lk.int    ; New Reno Mordino locker, no warning
{1325}{}{地圖}                          # rndtoxic.int    ; Random Toxic Map
{1326}{}{你看不到我}                    # ecirrad.int     ; critter that irradates
{1327}{}{錫人}                          # ecTinWod.int    ; Tin Woodsman
{1328}{}{地圖}                          # rndTinWd.int    ; Tin Woodsman Map Script
{1329}{}{石陣}                          # ecGrdFrv.int    ; Guardian of Forever
{1330}{}{}                              # rndForvr.int    ; Guardian of Forever Rnd Enct Map Script
{1331}{}{終端機}                        # ecGrdTrm.int    ; Guardian of Forever Water Chip Terminal
{1332}{}{鎖櫃}                          # niEld2Lk.int    ; New Reno Eldridge "Locker" HARD LOCK
{1333}{}{}                              # SiRagobj.int    ; Uhh box that Rondo cares
{1334}{}{地圖}                          # SFCHINA2.int    ; China 2 map
{1335}{}{安全機器人}                    # WCDedBot.int    ; Fighting Bot that does nothing
{1336}{}{安全機器人}                    # KCWupass.int    ; Klamath Guard Robot under Toxic Caves
{1337}{}{鎖櫃}                          # viHarWch.int    ; VCty - Harry Watch Script
{1338}{}{鎖櫃}                          # viEdWch.int     ; VCty - Ed Watch Script
{1339}{}{鎖櫃}                          # viAndWch.int    ; VCty - Doc Andrew Watch Script
{1340}{}{鎖櫃}                          # viLynWch.int    ; VCty - Lynette Watch Script
{1341}{}{鎖櫃}                          # viGrgWch.int    ; VCty - Gregory Watch Script
{1342}{}{鎖櫃}                          # viCGWch1.int    ; VCty - Prison Door Watch Script
{1343}{}{鎖櫃}                          # viCGWch2.int    ; VCty - Greeting Watch Script
{1344}{}{鎖櫃}                          # viRNWch1.int    ; VCty - Randal1 Watch Script
{1345}{}{鎖櫃}                          # viRNWch2.int    ; VCty - Randal2 Watch Script
{1346}{}{鎖櫃}                          # viStkWch.int    ; VCty - Stark Watch Script
{1347}{}{鎖櫃}                          # viBarWch.int    ; VCty - Barkus Watch Script
{1348}{}{鎖櫃}                          # viVLWch1.int    ; VCty - Valerie1 Watch Script
{1349}{}{鎖櫃}                          # viVLWch2.int    ; VCty - Valerie2 Watch Script
{1350}{}{鎖櫃}                          # viWalWch.int    ; VCty - Wallace Watch Script
{1351}{}{鎖櫃}                          # viSkvWch.int    ; VCty - Greeting Watch Script
{1352}{}{鎖櫃}                          # viInWch1.int    ; VCty - InGrd Watch Script
{1353}{}{鎖櫃}                          # viInWch2.int    ; VCty - InGrd Watch Script
{1354}{}{鎖櫃}                          # viInWch3.int    ; VCty - InGrd Watch Script
{1355}{}{鎖櫃}                          # viFamWch.int    ; VCty - GenFam Watch Script
{1356}{}{鎖櫃}                          # viCsWch1.int    ; VCty - Cassidy Watch Script
{1357}{}{碼頭的流浪漢}                  # FCDocSqa.int    ; San Fran - Doc Squatter
{1358}{}{碼頭的小孩}                    # FCDocKid.int    ; San Fran - Doc Kids
{1359}{}{地圖}                          # RndWhale.int    ; Random Whale Script
{1360}{}{派西．克普}                    # gcPercy.int     ; Percy Crump, Gecko Merchant
{1361}{}{盒子}                          # giPerBox.int    ; Percy's Stock Box
{1362}{}{盒子}                          # giJnkBox.int    ; Gecko Junkyard Temp Inventory Box
{1363}{}{門}                            # niWriDor.int    ; New Reno Wright Room Door
{1364}{}{偉大的安安妮斯}                # dcAnan.int      ; The Great Ananias, Mummy Master
{1365}{}{地圖}                          # RndUVilg.int    ; Unwashed Villager map
{1366}{}{村人}                          # ECWash.int      ; Unwashed Villagers... Ug You figure out where they go.
{1367}{}{無知村民}                      # ECSpammr.int    ; Spammer in Unwashed Encounter
{1368}{}{地圖}                          # eiSanMap.int    ; Military Base San Francisco Map
{1369}{}{地圖}                          # RndShutl.int    ; Random Shuttle Map
{1370}{}{地圖}                          # rndParih.int    ; Random Pariah Map Script
{1371}{}{地圖}                          # rndBHead.int    ; Random Big Head map
{1372}{}{地圖}                          # rndcafe.int     ; Random Cafe Map
{1373}{}{核子可樂販賣機}                # ZINuke.int      ; Nuka-Cola Machine
{1374}{}{碼頭}                          # sfdock.int      ; map script for San Fran Dock
{1375}{}{門}                            # ciCrisDr.int    ; Chris's Door
{1376}{}{地雷}                          # rtlndmin.int    ; Redding Land Mines
{1377}{}{地雷}                          # wtlndmin.int    ; Sierra Depot Land Mines
{1378}{}{你的配偶}                      # ncExSpou.int    ; New Reno Ex-Spouse script
{1379}{}{梅爾}                          # ECMel.int       ; Mel that Dogmeat Creates.
{1380}{}{通風口}                        # ciVent.int      ; Vent into Navarro
{1381}{}{凱文}                          # ccKevin.int     ; Kevin in Navarro
{1382}{}{警鈴}                          # csAlarm.int     ; Navarro base on alert lights
{1383}{}{鎖櫃}                          # ciQunWch.int    ; Quincy Locker watch script
{1384}{}{鎖櫃}                          # ciRulWch.int    ; Raul Locker Watch Script
{1385}{}{鎖櫃}                          # ciCmdWch.int    ; Commanded Locker Watch Script
{1386}{}{}                              # SSSign.int      ; NCR Statue
{1387}{}{}                              # ctFob.int       ; Fob EXP Spatial Script
{1388}{}{}                              # ctPlans.int     ; Vertibird EXP Spatial Script
{1389}{}{}                              # ctK9Part.int    ; K9 Part EXP Spatial Script
{1390}{}{}                              # csArea2.int     ; Script to signal if dude enters an area
{1391}{}{}                              # csOpen2.int     ; Script to signal if dude uses door w/o permision (in Navarro)
{1392}{}{}                              # ctSound.int     ; Soundproof Room Spatial Script
{1393}{}{}                              # csOpen3.int     ; Script to signal if dude uses door w/o permis
{1394}{}{私販酒者}                      # ECTlkMon.int    ; Talking Moonshiners
{1395}{}{}                              # ziWeakLk.int    ; Generic Weak Lock Watch Script
{1396}{}{}                              # ziMedmLk.int    ; Generic Medium Lock Watch Script
{1397}{}{馬戲團小孩}                    # dcCarnKd.int    ; Carny Kid - The Den
{1398}{}{}                              # ciDocWch.int    ; Raul Locker Watch Script
{1399}{}{}                              # ziHardLk.int    ; Generic Hard Lock Watch Script
{1400}{}{地雷}                          # CIMine.int      ; Mines in Raiders Cave
{1401}{}{鎖櫃}                          # niBisHLk.int    ; New Reno Bishop Hard Locker
{1402}{}{門}                            # niBisHDr.int    ; New Reno Bishop Hard Locked Door
{1403}{}{}                              # ntRicRom.int    ; New Reno Richard Wright Room Spacial
{1404}{}{}                          # MIMirDor.int    ; Miria's Bedroom Door  
{1405}{}{}                          # MIDavDor.int    ; Davin's Bedroom Door 
{1406}{}{}                          # SIPtbox2.int    ; box where Merk hides your car trunk stuff
{1407}{}{}                          # sfshutl1.int    ; map script to Hubologist entrance (shuttle)
{1408}{}{}                          # patchinf.int    ; patchinf
