#############################################################
#  Message File: ACSporPL.msg                               #
#                                                           #
#       Body Type:  Spore Plant(Plant with Dark Soul)       #
#       Combat AI: ?                                        #
#       Weapons: ?                                          #
#       HP: ?                                               #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: December 01, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{你看到一株黑暗植物。}
{101}{}{這些植物不只單是對花園有害而已，他們也有著攻擊人類的能力。}
{102}{}{這些植物是變種的結果。}
{103}{}{這些植物除了會攻擊人類之外，沒有什麼特別的了。}

#############################################################
#  The following lines are for the dialog which the NPC     #
#  says. This will be disorganized because of the Design    #
#  Tool.                                                    #
#############################################################
{150}{}{你得要將花園中所有的黑暗植物都給除掉。}
