# Player uses a skill on the door
# Unlock Door
{170}{}{你隨便的嘗試著打開鎖櫃上的鎖。}
{171}{}{你三流的技術把那個鎖給卡住了。}
{172}{}{你開鎖失敗了。}

# Unlock Door
{173}{}{隨便的嘗試著打開鎖櫃上的鎖。}
{174}{}{三流的技術把那個鎖給卡住了。}
{175}{}{開鎖失敗了。}

# Player uses an item on the door
{176}{}{你把門上的鎖給撞開了。}
{177}{}{你嘗試把所用蠻力打開，但是你傷到了你的背。你失去了一點生命質。}

# The following set of lines is to be translated as:
# You strain your back while trying to bust the lock and
# take [x] points of damage.

{178}{}{你閃到了你的腰，遭到了}
{179}{}{點傷害。}
{180}{}{你力量不夠，無法將鎖打開。}

# NPC uses an item on the door
# The following lines are prepended by the NPC's name
{181}{}{把所給撞開了。}
{182}{}{嘗試把所用蠻力打開，但是傷到了背。失去了一點生命質。}

# The following line set of lines is to be translated as:
# NPC strains his back while trying to bust the lock and
# takes [x] points of damage

{183}{}{在撞鎖的時候閃到了腰，受到了}
{184}{}{點的生命值。}

{185}{}{力量不夠，無法把鎖撞開。}
{186}{}{嘗試把所用蠻力打開，但是傷到了背。失去了一點生命質。}

# The following line set of lines is to be translated as:
# NPC strains her back while trying to bust the lock and
# takes [x] points of damage

{187}{}{撞鎖時閃到了腰，遭到了}
{188}{}{點傷害。}

# Lock Door
{189}{}{你把鎖鎖上了。}
{190}{}{你無法把鎖鎖上。}

# Lock Door
{191}{}{把鎖鎖上了。}
{192}{}{無法把鎖鎖上。}

{203}{}{鎖櫃看起來是鎖上的。}

{800}{}{你得到了ＦＯＢ。}
{810}{}{你得到了設計圖。}
{820}{}{你得到了Ｋ－９的移動器。}
