#############################################################
#							    #
#  Message File: dcPetey.msg				    #
#							    #
#  Note: Characters within curly braces (like line 100)     #
#	 will be read in as a message string. Caution	    #
#	 should be used when making comments. All comments  #
#	 should be prepended with a pound symbol for	    #
#	 visual ease. This does not comment out the line    #
#	 though.					    #
#							    #
#  Purpose: This message file contains the dialog for a     #
#	    new character from which is used by the	    #
#	    design tool. It will be updated using the	    #
#	    the tool. This is just a tool file, and not     #
#	    meant to be used in the game.		    #
#							    #
#  Log: Please note any changes that have been made to this #
#	file and comment which lines have changed.	    #
#							    #
#  Created: January 12, 1998				    #
#							    #
#  Updated:						    #
#############################################################

#############################################################
#  The following lines are for describing the item when     #
#  glanced and examined.				    #
#############################################################

{100}{}{你看見一個癮君子。}
{101}{}{你看見彼特。}

{150}{}{這是個可憐的癮君子。}
{151}{}{彼特看起來好像很需要別人幫助他。}
{152}{}{[談話]}
{155}{}{[咳、咳]有零錢可以施捨給彼特嗎？}
{156}{}{當然，拿去吧。}
{157}{}{沒有，滾蛋。}
{158}{}{彼大．．？}
{159}{}{謝謝。}
{160}{}{抱歉，再見。}
{161}{}{不用客氣了。}
{162}{}{下次好了，無論如何，謝謝了。}
{163}{}{[完成]}
{164}{}{非常的謝謝你。}
{165}{}{不用客氣。}
{166}{}{是啊。}
{167}{}{請問你可以幫助我這個可憐人嗎？}
{168}{}{給你$5。}
{169}{}{今天我不想要幫助別人。}
{170}{}{去找個工作吧，不要整天乞討。}
{171}{}{好心的小姐，請幫幫我這一個可憐人吧。}
{172}{}{你真可憐，給你$5。}
{173}{}{我從來都不給要飯的錢的。}
{174}{}{不！}

{200}{}{嘿，可以給我一些錢嗎？}
{201}{}{可以施捨點錢嗎？}
{202}{}{可以幫幫我嗎？}
{203}{}{施捨點錢吧！}
{204}{}{你能給點錢嗎？}
{205}{}{能給點錢嗎？}
{206}{}{給點錢嘛！}

{220}{}{請幫幫我。}
{221}{}{好疼啊。}
{222}{}{請幫幫我吧，好痛啊！}
{223}{}{小姐，你可以幫幫我嗎？}

{225}{}{真是謝謝你吧。}
{226}{}{嘿！你以為你在做什麼啊？}

{230}{}{感覺好舒服啊。}
{231}{}{嗯．．}
{232}{}{[笑著]}
{233}{}{嘿．．}

#dealer dead messages
#tubby dead
{300}{}{嘿，誰他媽的殺了塔比？}
{301}{}{塔比發生什麼事了？}
{302}{}{媽的，塔比他．．}
#generic
{303}{}{啊．．}
{304}{}{反正我也不喜歡他那混蛋．．}
#flick dead
{305}{}{富力克死了？可恨．．}
{306}{}{富力克發生什麼事了？}
{307}{}{富力克．．}

#dealer far, ask for assistance
#ask tubby
{310}{}{嘿，塔比．．我需要一些幫助。}
{311}{}{嘿！塔比！}
#ask any
{312}{}{你好。}
{313}{}{嘿！}
#ask flick
{314}{}{嘿，富力克，我需要一些幫助。}
{315}{}{嘿！富力克！}

#ask dealer for drug messages
#from tubby
{320}{}{嘿，塔比，你能夠幫我弄到一些貨嗎？我有錢的。}
{321}{}{嗯，塔比，我有一些錢。}
#from any
{322}{}{啊～～}
{323}{}{我需要一些毒品．．}
#from flick
{324}{}{嘿，富力克，你能夠幫我弄到一些貨嗎？我有錢的。}
{325}{}{嗯，富力克，我有一些錢。}

#thank dealer for drugs messages
#thank tubby
{330}{}{嗯．．再次的謝謝你，塔比。}
{331}{}{你真是夠朋友，塔比。}
#thank generic
{332}{}{謝了。}
{333}{}{你真夠朋友。}
#thank flick
{334}{}{嗯．．再次的謝謝你，富力克。}
{335}{}{你真是夠朋友，富力克。}
