#############################################################
#  Message File: diDiary.msg				    #
#							    #
#  Note: Characters within curly braces (like line 100)     #
#	 will be read in as a message string. Caution	    #
#	 should be used when making comments. All comments  #
#	 should be prepended with a pound symbol for	    #
#	 visual ease. This does not comment out the line    #
#	 though.					    #
#							    #
#  Purpose: This message file contains the dialog for a     #
#	    new character from which is used by the	    #
#	    design tool. It will be updated using the	    #
#	    the tool. This is just a tool file, and not     #
#	    meant to be used in the game.		    #
#							    #
#  Log: Please note any changes that have been made to this #
#	file and comment which lines have changed.	    #
#							    #
#  Created: January 13,1998				    #
#							    #
#  Updated:						    #
#############################################################

#############################################################
#  The following lines are for describing the item when     #
#  glanced and and examined.				    #
#############################################################

{100}{}{你看見一本很老舊的日記了。}
{101}{}{老舊的日記快要爛掉了。將資料下載到嗶嗶小子裡面。}
{102}{}{日記已經存在嗶嗶小子裡面了。}
