#############################################################
#  Message File: Klacanyn.msg				    #
#							    #
#  Created: August 18, 1998				    #
#							    #
#  Updated:						    #
#############################################################

#############################################################
#  The following lines are for the map script in describing #
#  what is happening when you first enter the map.	    #
#############################################################

{100}{}{你進來到了克拉馬斯附近的溪谷。}
