#############################################################
#  Message File: ModMain.msg                                #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the dialog for a     #
#           new character from which is used by the         #
#           design tool. It will be updated using the       #
#           the tool. This is just a tool file, and not     #
#           meant to be used in the game.                   #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#                                                           #
#  Created: January 15, 1998                                #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for the map script in describing #
#  what is happening when you first enter the map.          #
#############################################################

{100}{}{一個小的農村，它的周圍有許多已枯萎的農作物。}

# from the vermin hunter seed
{500}{}{看來我把他們都殺死了。}
{501}{}{所有老鼠都死了。}

# Coin Bag Descriptions
{600}{}{你看到一個錢袋。}
{601}{}{你看到一個錢袋，大概是有人許願將它丟到水池裡面的吧。}
{610}{}{這是我的夢想，我的希望，因此我要把它全部都拿回去。}

# KILL THEM ALL
{1000}{}{把他們都殺掉！}
{1001}{}{把史拉格都殺掉！}
{1002}{}{我要看著他們哀號！}
{1003}{}{讓我們去對付他們吧！}

# fall through floor
{1100}{}{你掉了15英呎，到了一個很暗的洞中。在牆上整齊的靠著許多的農耕工具。}

# blown out of hole
{1200}{}{在你剛剛離開那個洞穴時，馬上就發生了爆炸，把你炸得飛出來了。}
