#############################################################
#  Message File: ZClScorp.msg				    #
#							    #
#	Body Type:  Lesser Scorpion			    #
#	Combat AI: Scorpion AI				    #
#	Weapons:					    #
#	HP: ?						    #
#	Skills to note: None				    #
#							    #
#  Log: 						    #
#							    #
#  Created: December 01, 1997				    #
#							    #
#  Updated:						    #
#############################################################

#############################################################
#  The following lines are for describing the NPC when	    #
#  glanced and and examined.				    #
#############################################################
{100}{}{你看到一隻毒蠍子。}
{500}{}{你已經將所有威脅雙頭牛的毒蠍子都除掉了。}
